services:
  mysqldb:
    build: mysql
    volumes:
      - falcon-mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    env_file:
      - secrets/mysql.env
    command: --mysql-native-password=ON
    restart: unless-stopped

  # cache:
  #   image: redis:alpine
  #   volumes: 
  #     - falcon-redis-cache:/data
  #   ports:
  #     - '6379:6379'
  #   # environment: 
  #   #   REDIS_HOST=cache
  #   #   REDIS_PORT=6379
  #   #   REDIS_PASSWORD=
  #   env_file:
  #     - ./secrets/cache.env
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 
      #--requirepass ${REDIS_PASSWORD}
    # restart: unless-stopped

  server:
    build: server
    volumes:
      - falcon-server-node_modules:/app/node_modules
      - ./server/src:/app
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/mysql.env
      - ./secrets/auth.env
      # - ./secrets/cache.env
    depends_on:
      - mysqldb
      # - cache
    restart: unless-stopped

  react:
    build: react
    volumes:
      - ./react:/app
      - falcon-react-node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_REACT_APP_API_URL: http://localhost:3000/api

volumes:
  falcon-mysqldb-data:
  falcon-server-node_modules:
  # falcon-auth-node_modules:
  falcon-react-node_modules:
  # falcon-redis-cache:
