services:
  mysqldb:
    build: mysql
    volumes:
      - falcon-mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    #   - MYSQL_USER=
    #   - MYSQL_PASSWORD=
    env_file:
      - secrets/mysql.env
    command: --pid-file /app/mysqld.pid
    restart: unless-stopped

  # cache:
  #   image: redis:alpine
  #   volumes: 
  #     - falcon-redis-cache:/data
  #   # environment: 
  #   #   REDIS_HOST=cache
  #   #   REDIS_PORT=6379
  #   #   REDIS_PASSWORD=
  #   env_file:
  #     - ./secrets/cache.env
  #   command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   restart: unless-stopped

  server:
    build: server
    volumes:
      - falcon-server-node_modules:/app/node_modules
      - ./server/src:/app
    env_file:
      - ./secrets/mysql.env
      - ./secrets/auth.env
      # - ./secrets/cache.env
    depends_on:
      - mysqldb
      # - cache
    restart: unless-stopped

  auth:
    build: auth
    volumes: 
      - falcon-auth-node_modules:/app/node_modules
    env_file:
      - ./secrets/mysql.env
      - ./secrets/auth.env
    restart: unless-stopped

  pictures:
    build: pictures
    volumes: 
      - falcon-pictures-node_modules:/app/node_modules
      - ./pictures/pictures:/data/pictures
      # - falcon-pictures-data:/data
      - ./pictures/src:/app
    restart: unless-stopped

  react:
    build: react
    volumes:
      - ./react:/app
      - falcon-react-node_modules:/app/node_modules
    depends_on:
      - server
    environment:
      VITE_REACT_APP_API_URL: http://localhost/api
    restart: unless-stopped

  nginx:
    build: nginx
    ports:
      - "80:8000"
    depends_on:
      - server
      - react
      - pictures
    restart: unless-stopped

volumes:
  falcon-mysqldb-data:
  falcon-server-node_modules:
  falcon-pictures-node_modules:
  # falcon-pictures-data:
  falcon-react-node_modules:
  falcon-auth-node_modules:
  falcon-redis-cache:
