services:
  mysqldb:
    image: mysql:latest
    volumes:
      - ./mysql/mysql-dump:/docker-entrypoint-initdb.d
      - falcon-mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    env_file:
      - secrets/mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  server:
    build: server
    volumes:
      - falcon-server-node_modules:/app/node_modules
      - ./server/src:/app
    ports:
      - "3000:3000"
    env_file:
      - ./secrets/mysql.env
      - ./secrets/auth.env
    depends_on:
      - mysqldb

  react:
    build: react
    volumes:
      - ./react:/app
      - falcon-react-node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_REACT_APP_API_URL: http://localhost:3000/api

  # nginx:
  #   build: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #     - react

  ## Nginx Proxy Manager - Reverse Proxy with LetsEncrypt
  # npm:
  #   <<: *common-keys-core # See EXTENSION FIELDS at the top
  #   container_name: nginx-proxy-manager
  #   # Use the fully qualified name to pull including the docker.io portion
  #   image: 'docker.io/jc21/nginx-proxy-manager:latest'
  #   networks:
  #     - npm_proxy
  #   ports:
  #     - '80:80' # Public HTTP Port. Port Forwarding on Router is ON.
  #     - '443:443' # Public HTTPS Port. Port Forwarding on Router is ON.
  #     - '81:81' # Admin Web Port. Port Forwarding on Router is OFF. Internal Home Network Access only.
  #   volumes:
  #     - $DOCKERDIR/appdata/npm/config:/config 
  #     - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
  #     - $DOCKERDIR/appdata/npm/data:/data
  #   environment:
  #     DB_SQLITE_FILE: "/config/database.sqlite"
  #     DISABLE_IPV6: 'true'



volumes:
  falcon-mysqldb-data:
  falcon-server-node_modules:
  falcon-auth-node_modules:
  falcon-react-node_modules:
