services:
  mysqldb:
    image: mysql:latest
    volumes:
      - ./mysql/mysql-dump:/docker-entrypoint-initdb.d
      - falcon-mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    env_file:
      - secrets/mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  server:
    build: server
    volumes:
      - falcon-server-node_modules:/app/node_modules
      - ./server/src:/app
    ports:
      - "3000:80"
    env_file:
      - ./secrets/mysql.env
      - ./secrets/auth.env
    depends_on:
      - mysqldb

  react:
    build: react
    volumes:
      - ./react:/app
      - falcon-react-node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_REACT_APP_API_URL: http://localhost:3000/api

  # nginx:
  #   build: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - server
  #     - react


volumes:
  falcon-mysqldb-data:
  falcon-server-node_modules:
  falcon-auth-node_modules:
  falcon-react-node_modules:
