services:

   mysqldb:
      image: mysql:latest
      volumes:
         - ./mysql/mysql-dump:/docker-entrypoint-initdb.d
      ports:
         - "3306:3306"
      # environment:
      #   - MYSQL_USER=
      #   - MYSQL_PASSWORD=
      env_file:
         - secrets/mysql.env
      command: --default-authentication-plugin=mysql_native_password
      restart: always

   server:
      build: server
      volumes:
         - ./server/src:/app
         - /app/node_modules
      environment:
         AUTH_SERVICE_SERVICE_HOST: auth-api
      ports:
         - "3000:80"
      env_file:
         - ./secrets/mysql.env
      depends_on:
         - mysqldb
         - auth-api

   auth-api:
      build: auth-api
      ports:
         - "8000:80"
      env_file:
         - ./secrets/mysql.env
      depends_on:
         - mysqldb

   angular:
      build: angular
      volumes: 
         - ./angular:/app
         - /app/node_modules
      ports:
         - "4200:4200"
      depends_on:
         - server

  #  npm:
  #     build: 
  #        context: ./dockerfiles
  #        dockerfile: npm.dockerfile
  #     volumes:
  #        - ./src:/var/www/html

  #  ng:
  #     build: 
  #        context: ./dockerfiles
  #        dockerfile: ng.dockerfile
  #     volumes:
  #        - ./src:/var/www/html
      
