export type Site = {
  siteId: number,
  cascadeCode: string,
  siteName: string,
  siteTypeId: number,
  siteTypeName: string,
  address: string,
  city: string,
  state: string,
  zipCode: string,
  county: string,
  latitude: number,
  longitude: number, 
  elevation: number, 
  structureTypeId: number,
  structureTypeName: string,
  repairPriorityId: number,
  repairPriorityName: string,
  timezoneId: number,
  timezoneName: string,
  regionId?: number,
  regionName?: string,
  l4MarketId?: number,
  l4MarketName?: string,
  l5MarketId?: number,
  l5MarketName?: string,
  orgClusterId?: number,
  orgClusterName?: string,
  createdByName: string,
  createDate: string,
  modifiedByName: string,
  modifiedDate: string,
};

export type Bts = {
  btsId: number,
  mscId: number,
  mscName: string, 
  clliCode: string, 
  bscId: number,
  bscName: string, 
  btsNumber: string,
  equipmentStatusId: number,
  equipmentStatusName: string, 
  equipmentVendorId: number,
  equipmentVendorName: string, 
  equipmentModelId: number,
  equipmentModelName: string, 
  onAirDate: string,
  createdByName: string,
  createDate: string,
  modifiedByName: string,
  modifiedDate: string,
};

export type Sector = {
  sectorId: number,
  sectorNumber: number, 
  azimuth: number, 
  heightAgl: number, 
  mechanicalTilt: number, 
  antennaId: number, 
  equipmentVendorId: number,
  equipmentVendorName: string, 
  antennaName: string,  
  horizontalBw: number,
  verticalBw: number, 
  gainDbi: number, 
  frontToBackRatio: number, 
  electricalTilt: number, 
  sectorCoverageTypeId: number, 
  sectorCoverageTypeName: string,  
  radiusMeters: number, 
  createdByName: string,  
  createDate: string,  
  modifiedByName: string,  
  modifiedDate: string,  
};

export type Carrier = {   
  carrierId: number, 
  btsId: number, 
  channelId: number, 
  channelNumber: number,
  carrierNumber: number, 
  carrierDesignationId: number, 
  carrierDesignationName: string,  
  carrierTypeId: number, 
  carrierTypeName: string,    
  sortKey: number,  
  equipmentStatusId: number, 
  equipmentStatusName: string, 
  onAirDate: string,  
  createdByName: string,  
  createDate: string,  
  modifieByName: string,  
  modifiedDate: string,  
};

export type Nearest = {
  cascadeCode: string,
  siteName?: string,
  address?: string,
  city?: string,
  state?: string,
  distanceMi: number,
  bearing?: string,
  azimith?: number,
};