import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.user.deleteMany({})

  const uFalcon = await prisma.user.create({data:{lastName: 'Falcon Automation'}});
  const uNrm = await prisma.user.create({data:{lastName: 'NRM Interface Auto'}});
  const uBrianKnight = await prisma.user.create({data:{firstName:'Brian', lastName: 'Knight'}});
  const uPhilHartman = await prisma.user.create({data:{firstName:'Phil', lastName: 'Hartman'}});
  const uKevinOliczak = await prisma.user.create({data:{firstName:'Kevin', lastName: 'Oleniczak'}});
  const uKevinSmith = await prisma.user.create({data:{firstName: 'James', lastName: 'Smith'}});
  await prisma.user.create({data:{firstName: 'Onaz', lastName: 'Ochai'}});
  await prisma.user.create({data:{firstName: 'Trampus', lastName: 'Selensky'}});
  await prisma.user.create({data:{firstName: 'Steve', lastName: 'Manuel'}});
  await prisma.user.create({data:{firstName: 'Eric', lastName: 'Blood'}});
  await prisma.user.create({data:{firstName: 'Rohan', lastName: 'Shah'}});
  await prisma.user.create({data:{firstName: 'Daniel', lastName: 'Jones'}});
  await prisma.user.create({data:{firstName: 'Amit', lastName: 'Duvani'}});
  await prisma.user.create({data:{firstName: 'Eric', lastName: 'Thompson'}});
  await prisma.user.create({data:{firstName: 'Sankalp', lastName: 'Jain'}});
  await prisma.user.create({data:{firstName: 'Heather', lastName: 'Bloomcamp'}});
  await prisma.user.create({data:{firstName: 'Eddie', lastName: 'Burnell'}});
  await prisma.user.create({data:{firstName: 'Bruce', lastName: 'Elliott'}});
  await prisma.user.create({data:{firstName: 'NAPOLEON', lastName: 'EVANGELISTA'}});
  await prisma.user.create({data:{firstName: 'YASSIN', lastName: 'ALI'}});
  await prisma.user.create({data:{firstName: 'ROEL', lastName: 'SIGUE'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'LIANG'}});
  await prisma.user.create({data:{firstName: 'RUSSELL', lastName: 'C LENIG'}});
  await prisma.user.create({data:{firstName: 'SANKALP', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'THOMAS', lastName: 'BRADDOCK'}});
  await prisma.user.create({data:{firstName: 'ALAN', lastName: 'HARRIS'}});
  await prisma.user.create({data:{firstName: 'ANUBHA', lastName: 'MARWAH'}});
  await prisma.user.create({data:{firstName: 'ABHINAY', lastName: 'MANBANSH'}});
  await prisma.user.create({data:{firstName: 'ANAMIKA', lastName: 'VERMA'}});
  await prisma.user.create({data:{firstName: 'SANDEEP', lastName: 'RAWAT'}});
  await prisma.user.create({data:{firstName: 'Sunil', lastName: 'Alluri'}});
  await prisma.user.create({data:{firstName: 'BRUCE', lastName: 'TRAMMELL'}});
  await prisma.user.create({data:{firstName: 'STEPHANIE', lastName: 'COTTON'}});
  await prisma.user.create({data:{firstName: 'RAYMOND', lastName: 'ONGEWE'}});
  await prisma.user.create({data:{firstName: 'MANUEL', lastName: 'VILLANUEVA'}});
  await prisma.user.create({data:{firstName: 'JULIE', lastName: 'OPPEGARD'}});
  await prisma.user.create({data:{firstName: 'SHACHI', lastName: 'AGARWAL'}});
  await prisma.user.create({data:{firstName: 'MAYANK', lastName: 'VISHWAKARMA'}});
  await prisma.user.create({data:{firstName: 'ANUJ', lastName: 'GARG'}});
  await prisma.user.create({data:{firstName: 'VINCENT', lastName: 'CAPO'}});
  await prisma.user.create({data:{firstName: 'JAMES', lastName: 'MCMILLAN'}});
  await prisma.user.create({data:{firstName: 'SHAWN', lastName: 'KOHOUT'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'LESCZYNSKI'}});
  await prisma.user.create({data:{firstName: 'NICHOLAS', lastName: 'THOMAS'}});
  await prisma.user.create({data:{firstName: 'SANUJ', lastName: 'PACHOURI'}});
  await prisma.user.create({data:{firstName: 'ERICK', lastName: 'ORILLE'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'HOLT'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'LOPEZ'}});
  await prisma.user.create({data:{firstName: 'DIKSHA', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'SURENDER', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'RONALD', lastName: 'MAPILI'}});
  await prisma.user.create({data:{firstName: 'DARREL', lastName: 'ALLEN'}});
  await prisma.user.create({data:{firstName: 'TOM', lastName: 'ROWE'}});
  await prisma.user.create({data:{firstName: 'KEVIN', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'ARUN', lastName: 'PILLAI'}});
  await prisma.user.create({data:{firstName: 'BRETT', lastName: 'GRAY'}});
  await prisma.user.create({data:{firstName: 'RON', lastName: 'HALL'}});
  await prisma.user.create({data:{firstName: 'DEEPAK', lastName: 'R'}});
  await prisma.user.create({data:{firstName: 'TARUN', lastName: 'KHATRI'}});
  await prisma.user.create({data:{firstName: 'RAYMOND', lastName: 'JAVELONA'}});
  await prisma.user.create({data:{firstName: 'BENJAMIN', lastName: 'THURMOND'}});
  await prisma.user.create({data:{firstName: 'BRIAN', lastName: 'ROBBINS'}});
  await prisma.user.create({data:{firstName: 'TUAN', lastName: 'VU'}});
  await prisma.user.create({data:{firstName: 'PERRY', lastName: 'TURNER'}});
  await prisma.user.create({data:{firstName: 'CLEMENT', lastName: 'JIBOYE'}});
  await prisma.user.create({data:{firstName: 'STEPHEN', lastName: 'KARTZ'}});
  await prisma.user.create({data:{firstName: 'MUHAMMAD', lastName: 'BHUTTO'}});
  await prisma.user.create({data:{firstName: 'MICHAEL', lastName: 'LAWSON'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'SISSON'}});
  await prisma.user.create({data:{firstName: 'HATEM', lastName: 'RIZK'}});
  await prisma.user.create({data:{firstName: 'KEITH', lastName: 'WRIGHT'}});
  await prisma.user.create({data:{firstName: 'DIVYA', lastName: 'GANESH'}});
  await prisma.user.create({data:{firstName: 'NITIN', lastName: 'MUKHERJEE'}});
  await prisma.user.create({data:{firstName: 'DEVENDER', lastName: 'VERMA'}});
  await prisma.user.create({data:{firstName: 'SADANAND', lastName: 'KHEDKAR'}});
  await prisma.user.create({data:{firstName: 'ATUL', lastName: 'TIWARI'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'GOWANS'}});
  await prisma.user.create({data:{firstName: 'VARUN', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'AJIT', lastName: 'PRASHAR'}});
  await prisma.user.create({data:{firstName: 'MICHAEL', lastName: 'VINCENYO'}});
  await prisma.user.create({data:{firstName: 'JIM', lastName: 'DELLAROCCO'}});
  await prisma.user.create({data:{firstName: 'JOJO', lastName: 'GOEL'}});
  await prisma.user.create({data:{firstName: 'STEVEN', lastName: 'BEESON'}});
  await prisma.user.create({data:{firstName: 'JEFF', lastName: 'DIMARCO'}});
  await prisma.user.create({data:{firstName: 'LOUIS', lastName: 'MONTOYA'}});
  await prisma.user.create({data:{firstName: 'MOHIT', lastName: 'MATHUR'}});
  await prisma.user.create({data:{firstName: 'MITCHELL', lastName: 'JORDAN'}});
  await prisma.user.create({data:{firstName: 'CHIA', lastName: 'CHANG'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'JONES'}});
  await prisma.user.create({data:{firstName: 'HECTOR', lastName: 'ESTRELLA'}});
  await prisma.user.create({data:{firstName: 'SEAN', lastName: 'TOKARZ'}});
  await prisma.user.create({data:{firstName: 'ROSHAN', lastName: 'KUMAR'}});
  await prisma.user.create({data:{firstName: 'TEDEDRIA', lastName: 'COLLETON'}});
  await prisma.user.create({data:{firstName: 'BOK', lastName: 'TYE'}});
  await prisma.user.create({data:{firstName: 'SOLOMON', lastName: 'STATEN'}});
  await prisma.user.create({data:{firstName: 'VANN', lastName: 'SIV'}});
  await prisma.user.create({data:{firstName: 'SUMEET', lastName: 'ANEJA'}});
  await prisma.user.create({data:{firstName: 'HECTOR', lastName: 'RIEGO'}});
  await prisma.user.create({data:{firstName: 'SOURUB', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'EDGAR', lastName: 'MCDONIEL'}});
  await prisma.user.create({data:{firstName: 'DUBEY', lastName: 'POOJA'}});
  await prisma.user.create({data:{firstName: 'RODRIGO', lastName: 'RODELAS'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'PRICE'}});
  await prisma.user.create({data:{firstName: 'LINGGUANG', lastName: 'HAN'}});
  await prisma.user.create({data:{firstName: 'STEVEN', lastName: 'COOPER'}});
  await prisma.user.create({data:{firstName: 'CEDRIC', lastName: 'PHILLIPS'}});
  await prisma.user.create({data:{firstName: 'FELIPE', lastName: 'FUENTES'}});
  await prisma.user.create({data:{firstName: 'SHASHANK', lastName: 'SHEKHAR'}});
  await prisma.user.create({data:{firstName: 'AADESH', lastName: 'SHINDE'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'MOORE'}});
  await prisma.user.create({data:{firstName: 'RODERICK', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'KEVIN', lastName: 'MCCULLOUGH'}});
  await prisma.user.create({data:{firstName: 'SHAWN', lastName: 'WILLIAMS'}});
  await prisma.user.create({data:{firstName: 'KOUSHIK', lastName: 'RAY'}});
  await prisma.user.create({data:{firstName: 'AJIT', lastName: 'MATHEW'}});
  await prisma.user.create({data:{firstName: 'AMANDEEP', lastName: 'MAKKAR'}});
  await prisma.user.create({data:{firstName: 'ANDREW', lastName: 'FUDGE'}});
  await prisma.user.create({data:{firstName: 'PHILLIP', lastName: 'NORMAN'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'WILLIAMS'}});
  await prisma.user.create({data:{firstName: 'VINEET', lastName: 'MISHRA'}});
  await prisma.user.create({data:{firstName: 'KANIKA', lastName: 'CHHABRA'}});
  await prisma.user.create({data:{firstName: 'HIMANSHU', lastName: 'TIWARI'}});
  await prisma.user.create({data:{firstName: 'SHIVANSHU', lastName: 'RAJAN'}});
  await prisma.user.create({data:{firstName: 'DANILO', lastName: 'GATUS'}});
  await prisma.user.create({data:{firstName: 'FAMA', lastName: 'LO'}});
  await prisma.user.create({data:{firstName: 'GLENN', lastName: 'SHAVER'}});
  await prisma.user.create({data:{firstName: 'JOSEPH', lastName: 'HOEFER'}});
  await prisma.user.create({data:{firstName: 'Kevin', lastName: 'Farr'}});
  await prisma.user.create({data:{firstName: 'MICHELLE', lastName: 'RHODES'}});
  await prisma.user.create({data:{firstName: 'HECTOR', lastName: 'GONZALEZ'}});
  await prisma.user.create({data:{firstName: 'NEE NEE', lastName: 'YANG'}});
  await prisma.user.create({data:{firstName: 'HIMANSHU', lastName: 'GUPTA'}});
  await prisma.user.create({data:{firstName: 'KARA', lastName: 'MEINTASSIS'}});
  await prisma.user.create({data:{firstName: 'DONALD', lastName: 'COOK'}});
  await prisma.user.create({data:{firstName: 'WILLIAM', lastName: 'HASTINGS'}});
  await prisma.user.create({data:{firstName: 'MOHAN', lastName: 'KUPPUSAMY'}});
  await prisma.user.create({data:{firstName: 'RAJEEV', lastName: 'KUMAR'}});
  await prisma.user.create({data:{firstName: 'T J', lastName: 'COLLINS'}});
  await prisma.user.create({data:{firstName: 'KRISTEN', lastName: 'BRYANT'}});
  await prisma.user.create({data:{firstName: 'NITESH', lastName: 'NAINI'}});
  await prisma.user.create({data:{firstName: 'BRIAN', lastName: 'NASS'}});
  await prisma.user.create({data:{firstName: 'RAJ', lastName: 'PUTHANKATTIL'}});
  await prisma.user.create({data:{firstName: 'TANUJ', lastName: 'HASIJA'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'MURDOCH'}});
  await prisma.user.create({data:{firstName: 'DEEPINDER', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'STEVEN', lastName: 'MURDOCH'}});
  await prisma.user.create({data:{firstName: 'KUNTAL', lastName: 'SHAH'}});
  await prisma.user.create({data:{firstName: 'SHAILENDRA', lastName: 'PANDEY'}});
  await prisma.user.create({data:{firstName: 'SRINIVAS', lastName: 'KANYAGUGUNDLA'}});
  await prisma.user.create({data:{firstName: 'JESUS', lastName: 'VILLANUEVA'}});
  await prisma.user.create({data:{firstName: 'DOUA', lastName: 'LO'}});
  await prisma.user.create({data:{firstName: 'JUAN', lastName: 'TORRES JR'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'MURPHY'}});
  await prisma.user.create({data:{firstName: 'ALEX', lastName: 'DETRICK'}});
  await prisma.user.create({data:{firstName: 'BRADLEY', lastName: 'GRAY'}});
  await prisma.user.create({data:{firstName: 'ANIL', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'ANNE', lastName: 'NEMER'}});
  await prisma.user.create({data:{firstName: 'ANIL', lastName: 'RATHOR'}});
  await prisma.user.create({data:{firstName: 'JASON', lastName: 'ROUSE'}});
  await prisma.user.create({data:{firstName: 'KELLY', lastName: 'KREKEL'}});
  await prisma.user.create({data:{firstName: 'SONAL', lastName: 'GOEL'}});
  await prisma.user.create({data:{firstName: 'RAMIN', lastName: 'AGHAZADEH'}});
  await prisma.user.create({data:{firstName: 'JONEL', lastName: 'STANCU'}});
  await prisma.user.create({data:{firstName: 'CHAD', lastName: 'YARMER'}});
  await prisma.user.create({data:{firstName: 'VIVEK', lastName: 'KUMAR'}});
  await prisma.user.create({data:{firstName: 'MARVIN', lastName: 'ISHRAIDI'}});
  await prisma.user.create({data:{firstName: 'LYDIA', lastName: 'TRUJILLO'}});
  await prisma.user.create({data:{firstName: 'ARUN', lastName: 'KULKARNI'}});
  await prisma.user.create({data:{firstName: 'VIKASH', lastName: 'SRIVASTAVA'}});
  await prisma.user.create({data:{firstName: 'SHUBHA', lastName: 'KOUNDINYAN'}});
  await prisma.user.create({data:{firstName: 'WILLIAM', lastName: 'JOHNSON'}});
  await prisma.user.create({data:{firstName: 'LENG', lastName: 'CHHENG'}});
  await prisma.user.create({data:{firstName: 'AADESH', lastName: 'MURTHYKEYAN'}});
  await prisma.user.create({data:{firstName: 'TOM', lastName: 'NGUYEN'}});
  await prisma.user.create({data:{firstName: 'BOB', lastName: 'POORBAUGH'}});
  await prisma.user.create({data:{firstName: 'GENARO', lastName: 'MEJIA'}});
  await prisma.user.create({data:{firstName: 'REINALDO', lastName: 'CORDERO'}});
  await prisma.user.create({data:{firstName: 'VIRGIL', lastName: 'ROBINSON JR'}});
  await prisma.user.create({data:{firstName: 'DUSTY', lastName: 'WYMAN'}});
  await prisma.user.create({data:{firstName: 'MANISH', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'DION', lastName: 'PITTMAN'}});
  await prisma.user.create({data:{firstName: 'NEERAJ', lastName: 'HAMPAL'}});
  await prisma.user.create({data:{firstName: 'YOSEF', lastName: 'HAILE'}});
  await prisma.user.create({data:{firstName: 'SANDEEP', lastName: 'JAIN'}});
  await prisma.user.create({data:{firstName: 'RODYNA', lastName: 'ZIDAN'}});
  await prisma.user.create({data:{firstName: 'RESTY', lastName: 'IGNACIO'}});
  await prisma.user.create({data:{firstName: 'CYRUS', lastName: 'RAISZADEH'}});
  await prisma.user.create({data:{firstName: 'SHIDEH', lastName: 'DALILALTOJARY'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'PANGAN'}});
  await prisma.user.create({data:{firstName: 'HIMANI', lastName: 'BANSAL'}});
  await prisma.user.create({data:{firstName: 'AMIT', lastName: 'VERMA'}});
  await prisma.user.create({data:{firstName: 'SATISH', lastName: 'KHULLAR'}});
  await prisma.user.create({data:{firstName: 'ASEEM', lastName: 'MOUDGIL'}});
  await prisma.user.create({data:{firstName: 'MELISSA', lastName: 'SY-TU'}});
  await prisma.user.create({data:{firstName: 'Kevin', lastName: 'Reed'}});
  await prisma.user.create({data:{firstName: 'MAURICIO', lastName: 'LOPEZ'}});
  await prisma.user.create({data:{firstName: 'PERWAIZ', lastName: 'AKHTAR'}});
  await prisma.user.create({data:{firstName: 'GLENN', lastName: 'TORSHIZI'}});
  await prisma.user.create({data:{firstName: 'DHRUV', lastName: 'NEGI'}});
  await prisma.user.create({data:{firstName: 'MALA', lastName: 'GARG'}});
  await prisma.user.create({data:{firstName: 'YUE', lastName: 'YOA'}});
  await prisma.user.create({data:{firstName: 'MOHAMMED', lastName: 'BENNANI'}});
  await prisma.user.create({data:{firstName: 'HENOK', lastName: 'MENGISTU'}});
  await prisma.user.create({data:{firstName: 'KUMI', lastName: 'EASWARACHANDRAN'}});
  await prisma.user.create({data:{firstName: 'DAI', lastName: 'NGO'}});
  await prisma.user.create({data:{firstName: 'MOHAMED', lastName: 'BENCHAABOUNE'}});
  await prisma.user.create({data:{firstName: 'KARIMI', lastName: 'KIRAGU'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'HEET'}});
  await prisma.user.create({data:{firstName: 'MICHAEL', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'HARJEET', lastName: 'JANDU'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'TEEL'}});
  await prisma.user.create({data:{firstName: 'NAMIT', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'ANIL', lastName: 'PILLARISETTI'}});
  await prisma.user.create({data:{firstName: 'RAJVI', lastName: 'BHATT'}});
  await prisma.user.create({data:{firstName: 'CRAIG', lastName: 'CATENA'}});
  await prisma.user.create({data:{firstName: 'GAURAV', lastName: 'NANDOLA'}});
  await prisma.user.create({data:{firstName: 'CONRAD', lastName: 'ABAD'}});
  await prisma.user.create({data:{firstName: 'RAHUL', lastName: 'SAWANT'}});
  await prisma.user.create({data:{firstName: 'ANTHONY', lastName: 'PERALTA'}});
  await prisma.user.create({data:{firstName: 'RYAN', lastName: 'HUYNH'}});
  await prisma.user.create({data:{firstName: 'FREDY', lastName: 'CHINOY'}});
  await prisma.user.create({data:{firstName: 'YOMI', lastName: 'OKE'}});
  await prisma.user.create({data:{firstName: 'GAURAV', lastName: 'NUKALA'}});
  await prisma.user.create({data:{firstName: 'KRISTA', lastName: 'PHILLIPS'}});
  await prisma.user.create({data:{firstName: 'VIOLETA', lastName: 'TABLETT'}});
  await prisma.user.create({data:{firstName: 'MAHESH', lastName: 'BABU'}});
  await prisma.user.create({data:{firstName: 'CHETAN', lastName: 'PATEL'}});
  await prisma.user.create({data:{firstName: 'GURINDER', lastName: 'BIR-SINGH'}});
  await prisma.user.create({data:{firstName: 'GEZAHEGN', lastName: 'KIFLE'}});
  await prisma.user.create({data:{firstName: 'PRATIK', lastName: 'MANKAR'}});
  await prisma.user.create({data:{firstName: 'ALWYN', lastName: 'DIPPENAAR'}});
  await prisma.user.create({data:{firstName: 'DIEM', lastName: 'LE'}});
  await prisma.user.create({data:{firstName: 'STEPHEN', lastName: 'HEFFELFINGER'}});
  await prisma.user.create({data:{firstName: 'ANTONIO', lastName: 'GAJO'}});
  await prisma.user.create({data:{firstName: 'MAYSA', lastName: 'ALMONAYER'}});
  await prisma.user.create({data:{firstName: 'MUSTAPHA', lastName: 'RACHIDI'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'LININGER'}});
  await prisma.user.create({data:{firstName: 'HANUMAT', lastName: 'NOONEY'}});
  await prisma.user.create({data:{firstName: 'IBRAHIM', lastName: 'LAHLOU'}});
  await prisma.user.create({data:{firstName: 'ANUJ', lastName: 'GOEL'}});
  await prisma.user.create({data:{firstName: 'RISHABH', lastName: 'PARMAR'}});
  await prisma.user.create({data:{firstName: 'KRITI', lastName: 'ARORA'}});
  await prisma.user.create({data:{firstName: 'SRINATH', lastName: 'MADIPALLI'}});
  await prisma.user.create({data:{firstName: 'VINCENT', lastName: 'MOISE'}});
  await prisma.user.create({data:{firstName: 'STEPHEN', lastName: 'BURNEY'}});
  await prisma.user.create({data:{firstName: 'RICK', lastName: 'ANDRAS'}});
  await prisma.user.create({data:{firstName: 'COLLEEN', lastName: 'HALLEY'}});
  await prisma.user.create({data:{firstName: 'ALEJANDRO', lastName: 'ZARATE'}});
  await prisma.user.create({data:{firstName: 'MEHTA', lastName: 'J'}});
  await prisma.user.create({data:{firstName: 'ATANU', lastName: 'HALDER'}});
  await prisma.user.create({data:{firstName: 'JONATHAN', lastName: 'HULL'}});
  await prisma.user.create({data:{firstName: 'DEREK', lastName: 'DRAGISICH'}});
  await prisma.user.create({data:{firstName: 'SOURABH', lastName: 'JAIN'}});
  await prisma.user.create({data:{firstName: 'ARUN', lastName: 'GOYAL'}});
  await prisma.user.create({data:{firstName: 'AKANKSHA', lastName: 'AGRAWAL'}});
  await prisma.user.create({data:{firstName: 'SMRITI', lastName: 'KAPOOR'}});
  await prisma.user.create({data:{firstName: 'KRISHNAKUMAR', lastName: 'HARIHARAN'}});
  await prisma.user.create({data:{firstName: 'KAJARI', lastName: 'ARYA'}});
  await prisma.user.create({data:{firstName: 'AISHWARYA', lastName: 'PATHAK'}});
  await prisma.user.create({data:{firstName: 'JARED', lastName: 'ELLIOTT'}});
  await prisma.user.create({data:{firstName: 'SANDEEP', lastName: 'CHITTIMURI'}});
  await prisma.user.create({data:{firstName: 'ASHISH', lastName: 'MITTAL'}});
  await prisma.user.create({data:{firstName: 'PHILIP', lastName: 'SORTIN'}});
  await prisma.user.create({data:{firstName: 'MILENA', lastName: 'IGNJATOVIC'}});
  await prisma.user.create({data:{firstName: 'ADWAIT', lastName: 'JAWALE'}});
  await prisma.user.create({data:{firstName: 'RAGHVENDRA', lastName: 'AGNIHOTRI'}});
  await prisma.user.create({data:{firstName: 'ABDELGHANI', lastName: 'MOUFJI'}});
  await prisma.user.create({data:{firstName: 'SANDEEP', lastName: 'GOYAL'}});
  await prisma.user.create({data:{firstName: 'MANISHA', lastName: 'GOYAL'}});
  await prisma.user.create({data:{firstName: 'SUDHIR', lastName: 'JAGADEESHAN'}});
  await prisma.user.create({data:{firstName: 'KEITH', lastName: 'VELLANTE'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'MALUPIN'}});
  await prisma.user.create({data:{firstName: 'JIMMY', lastName: 'XU'}});
  await prisma.user.create({data:{firstName: 'HARVEY', lastName: 'CHEUNG'}});
  await prisma.user.create({data:{firstName: 'ANOOP', lastName: 'GOYAL'}});
  await prisma.user.create({data:{firstName: 'MURUGABIRAN', lastName: 'JAYAPAL'}});
  await prisma.user.create({data:{firstName: 'ARNAV', lastName: 'MISHRA'}});
  await prisma.user.create({data:{firstName: 'GAURAV', lastName: 'AWASTHEE'}});
  await prisma.user.create({data:{firstName: 'JEAN', lastName: 'ALEXIS'}});
  await prisma.user.create({data:{firstName: 'ALOK', lastName: 'SETU'}});
  await prisma.user.create({data:{firstName: 'NIKHIL', lastName: 'MANE'}});
  await prisma.user.create({data:{firstName: 'MUHAMMAD', lastName: 'IBRAHIM'}});
  await prisma.user.create({data:{firstName: 'JAD', lastName: 'ASSAAD'}});
  await prisma.user.create({data:{firstName: 'LAL', lastName: 'BHARWANI'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'SIHPOL'}});
  await prisma.user.create({data:{firstName: 'STEPHEN', lastName: 'MONT'}});
  await prisma.user.create({data:{firstName: 'AMAN', lastName: 'THAREJA'}});
  await prisma.user.create({data:{firstName: 'Raymond', lastName: 'Kim'}});
  await prisma.user.create({data:{firstName: 'JOSEPH', lastName: 'SUTHERLAND'}});
  await prisma.user.create({data:{firstName: 'FARHAN', lastName: 'CHAUDHRY'}});
  await prisma.user.create({data:{firstName: 'JULIE', lastName: 'HART'}});
  await prisma.user.create({data:{firstName: 'ASHISH', lastName: 'BRAMHE'}});
  await prisma.user.create({data:{firstName: 'MATTHEW', lastName: 'CHAN'}});
  await prisma.user.create({data:{firstName: 'YOGESH', lastName: 'SHAH'}});
  await prisma.user.create({data:{firstName: 'JEFFREY', lastName: 'WORMHOOD'}});
  await prisma.user.create({data:{firstName: 'ROHIT', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'CURTIS', lastName: 'PAGE'}});
  await prisma.user.create({data:{firstName: 'KIN', lastName: 'PHOON'}});
  await prisma.user.create({data:{firstName: 'Amy', lastName: 'Giesken'}});
  await prisma.user.create({data:{firstName: 'JATIN', lastName: 'CHAUDHARY'}});
  await prisma.user.create({data:{firstName: 'PATRICK', lastName: 'QUINN'}});
  await prisma.user.create({data:{firstName: 'TONY', lastName: 'SILVA'}});
  await prisma.user.create({data:{firstName: 'JOSEPH', lastName: 'WOOD'}});
  await prisma.user.create({data:{firstName: 'AJAY', lastName: 'SAWANT'}});
  await prisma.user.create({data:{firstName: 'SANJEEVI', lastName: 'BALASUBAMANIAN'}});
  await prisma.user.create({data:{firstName: 'FAZMIL', lastName: 'LUTHUFDEEN'}});
  await prisma.user.create({data:{firstName: 'AVTAR', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'Darrin', lastName: 'Mott'}});
  await prisma.user.create({data:{firstName: 'ADAM', lastName: 'DURANDO'}});
  await prisma.user.create({data:{firstName: 'KRISTEN', lastName: 'NICKERSON'}});
  await prisma.user.create({data:{firstName: 'FONDA', lastName: 'ONG'}});
  await prisma.user.create({data:{firstName: 'VISH', lastName: 'IYER'}});
  await prisma.user.create({data:{firstName: 'VIPUL', lastName: 'ARORA'}});
  await prisma.user.create({data:{firstName: 'ANKIT', lastName: 'SRIVASTAVA'}});
  await prisma.user.create({data:{firstName: 'JASLEEN', lastName: 'KAUR'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'FORNAGIEL'}});
  await prisma.user.create({data:{firstName: 'SEEMA', lastName: 'AHMED'}});
  await prisma.user.create({data:{firstName: 'RADU', lastName: 'ALECSANDRU'}});
  await prisma.user.create({data:{firstName: 'JEREMY', lastName: 'FULKERSON'}});
  await prisma.user.create({data:{firstName: 'CHAD', lastName: 'CHISHOLM'}});
  await prisma.user.create({data:{firstName: 'STEPHEN', lastName: 'JAYAKUMAR'}});
  await prisma.user.create({data:{firstName: 'JUSTIN', lastName: 'DARROW'}});
  await prisma.user.create({data:{firstName: 'William', lastName: 'Arseniu'}});
  await prisma.user.create({data:{firstName: 'JASON', lastName: 'HAGY'}});
  await prisma.user.create({data:{firstName: 'GILBERT', lastName: 'NYANDJO'}});
  await prisma.user.create({data:{firstName: 'THOMAS', lastName: 'FITZSIMMONS'}});
  await prisma.user.create({data:{firstName: 'HOLLIS', lastName: 'WIGGS'}});
  await prisma.user.create({data:{firstName: 'PALLAVI', lastName: 'GARG'}});
  await prisma.user.create({data:{firstName: 'Jeff', lastName: 'Patterson'}});
  await prisma.user.create({data:{firstName: 'SHANTE', lastName: 'CHAVIS'}});
  await prisma.user.create({data:{firstName: 'AMREEK', lastName: 'SAINI'}});
  await prisma.user.create({data:{firstName: 'HANI', lastName: 'ABUELGASIM'}});
  await prisma.user.create({data:{firstName: 'SUNIL', lastName: 'MHATRE'}});
  await prisma.user.create({data:{firstName: 'RICK', lastName: 'MADONI'}});
  await prisma.user.create({data:{firstName: 'PHILLIP', lastName: 'SHEEK JR'}});
  await prisma.user.create({data:{firstName: 'KEVIN', lastName: 'BROWN'}});
  await prisma.user.create({data:{firstName: 'NIDISH', lastName: 'VASHISTHA'}});
  await prisma.user.create({data:{firstName: 'ALFRED', lastName: 'LO'}});
  await prisma.user.create({data:{firstName: 'CURTIS', lastName: 'BUNNELL'}});
  await prisma.user.create({data:{firstName: 'MEENU', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'WILTSHIRE'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'CARTER'}});
  await prisma.user.create({data:{firstName: 'SAFWAT', lastName: 'HELMY'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER', lastName: 'HUFFMAN'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'RAFUSE'}});
  await prisma.user.create({data:{firstName: 'DIVAY', lastName: 'PASSI'}});
  await prisma.user.create({data:{firstName: 'AYMAN', lastName: 'SHAKFA'}});
  await prisma.user.create({data:{firstName: 'AZADWINDER', lastName: 'MAAN'}});
  await prisma.user.create({data:{firstName: 'MEGHA', lastName: 'PRAVEEN'}});
  await prisma.user.create({data:{firstName: 'DAVID P KIECHLE'}});
  await prisma.user.create({data:{firstName: 'DAVID KIECHLE'}});
  await prisma.user.create({data:{firstName: 'SANDEEP SINGH'}});
  await prisma.user.create({data:{firstName: 'PRAVEEN KUMAR'}});
  await prisma.user.create({data:{firstName: 'DAVID A THOMAS'}});
  await prisma.user.create({data:{firstName: 'EUGENE LOPEZ'}});
  await prisma.user.create({data:{firstName: 'CYRIL DINOPOL'}});
  await prisma.user.create({data:{firstName: 'HAMMAD R NAQVI'}});
  await prisma.user.create({data:{firstName: 'JIM RICKARD'}});
  await prisma.user.create({data:{firstName: 'ARNOLD ALVARADO'}});
  await prisma.user.create({data:{firstName: 'DAVID SCOTT'}});
  await prisma.user.create({data:{firstName: 'SAM S SALLIS'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER W BURDEN'}});
  await prisma.user.create({data:{firstName: 'CHAITANYA DABKE'}});
  await prisma.user.create({data:{firstName: 'SHREY GOYAL'}});
  await prisma.user.create({data:{firstName: 'SHIMPA MAHAJAN'}});
  await prisma.user.create({data:{firstName: 'ANKIT SARDA'}});
  await prisma.user.create({data:{firstName: 'CHANDRASHEKHAR P THOTE'}});
  await prisma.user.create({data:{firstName: 'BRIJMANI KUMAR'}});
  await prisma.user.create({data:{firstName: 'CHAD GRIEPP'}});
  await prisma.user.create({data:{firstName: 'SUMIT KUMAR M MISHRA'}});
  await prisma.user.create({data:{firstName: 'GREG STEPHEN'}});
  await prisma.user.create({data:{firstName: 'Cassandra L Meadows'}});
  await prisma.user.create({data:{firstName: 'LAUREN NEUBERGER'}});
  await prisma.user.create({data:{firstName: 'JAMES WEBER'}});
  await prisma.user.create({data:{firstName: 'RAVI.KUMAR.SINDHAL'}});
  await prisma.user.create({data:{firstName: 'ANAND MISHRA'}});
  await prisma.user.create({data:{firstName: 'LAUREN', lastName: 'OWEN'}});
  await prisma.user.create({data:{firstName: 'JEFF', lastName: 'TOSTENRUDE'}});
  await prisma.user.create({data:{firstName: 'VIVEK', lastName: 'DESAI'}});
  await prisma.user.create({data:{firstName: 'NATHAN', lastName: 'RAUSCH'}});
  await prisma.user.create({data:{firstName: 'CHRIS', lastName: 'CUBANSKE'}});
  await prisma.user.create({data:{firstName: 'YuWu', lastName: 'Zhang'}});
  await prisma.user.create({data:{firstName: 'ALAN', lastName: 'LIM'}});
  await prisma.user.create({data:{firstName: 'SAKET', lastName: 'CHANDAN'}});
  await prisma.user.create({data:{firstName: 'RACHEL', lastName: 'MCCRYSTAL'}});
  await prisma.user.create({data:{firstName: 'VINAY', lastName: 'BHATT'}});
  await prisma.user.create({data:{firstName: 'ROBERT CROWE'}});
  await prisma.user.create({data:{firstName: 'SOMENDRA DEODA'}});
  await prisma.user.create({data:{firstName: 'DINESH KUMAR MUTHU'}});
  await prisma.user.create({data:{firstName: 'GEORGE PIVKA'}});
  await prisma.user.create({data:{firstName: 'JANICE RIOS-NEGRON'}});
  await prisma.user.create({data:{firstName: 'SCOTT GERDTS'}});
  await prisma.user.create({data:{firstName: 'JASON BODNAR'}});
  await prisma.user.create({data:{firstName: 'Gunsheen Kaur'}});
  await prisma.user.create({data:{firstName: 'KELLEN EILER'}});
  await prisma.user.create({data:{firstName: 'PAUL ROOS'}});
  await prisma.user.create({data:{firstName: 'RICHARD LETTER'}});
  await prisma.user.create({data:{firstName: 'SHANE X EDWARDS'}});
  await prisma.user.create({data:{firstName: 'AKRITI SINHA'}});
  await prisma.user.create({data:{firstName: 'GAURAV SHARMA'}});
  await prisma.user.create({data:{firstName: 'GERALD L TINDALL'}});
  await prisma.user.create({data:{firstName: 'NEHA AGRAWAL'}});
  await prisma.user.create({data:{firstName: 'ASHUTOSH AGNIHOTRI'}});
  await prisma.user.create({data:{firstName: 'NHATTUAN HO'}});
  await prisma.user.create({data:{firstName: 'DHANESH GOEL'}});
  await prisma.user.create({data:{firstName: 'CHARLES GEORGE'}});
  await prisma.user.create({data:{firstName: 'JOSEPH L ARNETT'}});
  await prisma.user.create({data:{firstName: 'ABDUS SAMI MOHAMMED'}});
  await prisma.user.create({data:{firstName: 'HARRY BAUMGARTEN'}});
  await prisma.user.create({data:{firstName: 'NIMISH ADHVARYU'}});
  await prisma.user.create({data:{firstName: 'BIREN PATEL'}});
  await prisma.user.create({data:{firstName: 'DAN LAMKIN'}});
  await prisma.user.create({data:{firstName: 'DANIEL STACEY'}});
  await prisma.user.create({data:{firstName: 'FRAN SAUBER'}});
  await prisma.user.create({data:{firstName: 'BILL LESLIE'}});
  await prisma.user.create({data:{firstName: 'ANAND ARUMUGAM'}});
  await prisma.user.create({data:{firstName: 'MILAN SAVIC'}});
  await prisma.user.create({data:{firstName: 'TEJAS AMIN'}});
  await prisma.user.create({data:{firstName: 'BRYAN NARBERT'}});
  await prisma.user.create({data:{firstName: 'IGOR FORTEL'}});
  await prisma.user.create({data:{firstName: 'PRIYA PERUMALSAMY'}});
  await prisma.user.create({data:{firstName: 'JOTHAM HABTEMARIAM'}});
  await prisma.user.create({data:{firstName: 'JONAS BARCELLANO'}});
  await prisma.user.create({data:{firstName: 'JODY GLENN'}});
  await prisma.user.create({data:{firstName: 'MIKE CHOW'}});
  await prisma.user.create({data:{firstName: 'RUSH LUANGSUWAN'}});
  await prisma.user.create({data:{firstName: 'DANIELLE ANDERSON'}});
  await prisma.user.create({data:{firstName: 'TONY THOMPSON'}});
  await prisma.user.create({data:{firstName: 'ANTHONY IMRISEK'}});
  await prisma.user.create({data:{firstName: 'DAVE CHUKE'}});
  await prisma.user.create({data:{firstName: 'NEERAJ.BERI'}});
  await prisma.user.create({data:{firstName: 'JOHN CULLEN'}});
  await prisma.user.create({data:{firstName: 'ARMIL BIAG'}});
  await prisma.user.create({data:{firstName: 'NITIN AWASTHI'}});
  await prisma.user.create({data:{firstName: 'HAMMAD SHAIKH'}});
  await prisma.user.create({data:{firstName: 'SYED HASAN'}});
  await prisma.user.create({data:{firstName: 'KHALID MENAWI'}});
  await prisma.user.create({data:{firstName: 'ANAND ZAVERI'}});
  await prisma.user.create({data:{firstName: 'BYRON MOORE'}});
  await prisma.user.create({data:{firstName: 'LARRY CABROL'}});
  await prisma.user.create({data:{firstName: 'SHAHZAD HAROON'}});
  await prisma.user.create({data:{firstName: 'KARTHIK BHARATHAN'}});
  await prisma.user.create({data:{firstName: 'RAMYA NAGULAVANCHA'}});
  await prisma.user.create({data:{firstName: 'DAVID RAYMOND'}});
  await prisma.user.create({data:{firstName: 'PAUL PETERSON'}});
  await prisma.user.create({data:{firstName: 'ROBERT EGENOLF'}});
  await prisma.user.create({data:{firstName: 'DONALD BACH'}});
  await prisma.user.create({data:{firstName: 'ROHIT KAPUR'}});
  await prisma.user.create({data:{firstName: 'DANIEL A HUFFMAN'}});
  await prisma.user.create({data:{firstName: 'KENNEDY BRIGGS'}});
  await prisma.user.create({data:{firstName: 'GURUKRUPA KUMARASWAMY'}});
  await prisma.user.create({data:{firstName: 'PATRICK PHAN'}});
  await prisma.user.create({data:{firstName: 'JOEL BOUTIN'}});
  await prisma.user.create({data:{firstName: 'JOSEPH SMYK'}});
  await prisma.user.create({data:{firstName: 'DWAYNE LATZKE'}});
  await prisma.user.create({data:{firstName: 'CHRIS KREINER'}});
  await prisma.user.create({data:{firstName: 'DUANE TOMKA'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'SCHWITZER'}});
  await prisma.user.create({data:{firstName: 'P J', lastName: 'Kirkpatrick'}});
  await prisma.user.create({data:{firstName: 'RANDY', lastName: 'KRUSZKA'}});
  await prisma.user.create({data:{firstName: 'ELAINA', lastName: 'KOCH'}});
  await prisma.user.create({data:{firstName: 'KENNETH', lastName: 'BROWN'}});
  await prisma.user.create({data:{firstName: 'FREDA', lastName: 'Dacanay'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'MULLINS'}});
  await prisma.user.create({data:{firstName: 'JAMES', lastName: 'MCCOY'}});
  await prisma.user.create({data:{firstName: 'ADNAN', lastName: 'MUZAFFAR'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'MANLEY'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'HAUGHNEY'}});
  await prisma.user.create({data:{firstName: 'ANKIT', lastName: 'KATYAL'}});
  await prisma.user.create({data:{firstName: 'ROBBY', lastName: 'WILKERSON'}});
  await prisma.user.create({data:{firstName: '', lastName: 'ELLIOTT'}});
  await prisma.user.create({data:{firstName: 'MICHAEL', lastName: 'ROBINSON'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'MANLEY'}});
  await prisma.user.create({data:{firstName: 'DONALD', lastName: 'PIERCE'}});
  await prisma.user.create({data:{firstName: 'SUKHPREET', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'ROSS'}});
  await prisma.user.create({data:{firstName: 'LATISHA', lastName: 'LEACH'}});
  await prisma.user.create({data:{firstName: 'BRYAN', lastName: 'HIPPS'}});
  await prisma.user.create({data:{firstName: 'KEVIN', lastName: 'RODRIGUES'}});
  await prisma.user.create({data:{firstName: 'LEE', lastName: 'ROGERS'}});
  await prisma.user.create({data:{firstName: 'RICHARD', lastName: 'SUHOCKI'}});
  await prisma.user.create({data:{firstName: 'RISHABH', lastName: 'KAPOOR'}});
  await prisma.user.create({data:{firstName: 'PHILIP', lastName: 'CHURA'}});
  await prisma.user.create({data:{firstName: 'LAURA', lastName: 'HIGGINS'}});
  await prisma.user.create({data:{firstName: 'NADEEM', lastName: 'YOUNUS'}});
  await prisma.user.create({data:{firstName: 'TIMOTHY', lastName: 'NICHOLSON'}});
  await prisma.user.create({data:{firstName: 'BERNARD', lastName: 'MORELOS'}});
  await prisma.user.create({data:{firstName: 'LIANG', lastName: 'LI'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'PRACH'}});
  await prisma.user.create({data:{firstName: 'MASROOR', lastName: 'AHMAD'}});
  await prisma.user.create({data:{firstName: 'STEVEN', lastName: 'KEPHART'}});
  await prisma.user.create({data:{firstName: 'ROSIE', lastName: 'WILSON'}});
  await prisma.user.create({data:{firstName: 'WASIF', lastName: 'AYUB'}});
  await prisma.user.create({data:{firstName: 'JOHNNY', lastName: 'TUCKER'}});
  await prisma.user.create({data:{firstName: 'TODD', lastName: 'KOSTERMAN'}});
  await prisma.user.create({data:{firstName: 'HENRI', lastName: 'EDOH'}});
  await prisma.user.create({data:{firstName: 'DEEPENDRA', lastName: 'POKHARELI'}});
  await prisma.user.create({data:{firstName: 'RUSHI', lastName: 'RAVAL'}});
  await prisma.user.create({data:{firstName: 'ADNAN', lastName: 'KHAN'}});
  await prisma.user.create({data:{firstName: 'KARAN', lastName: 'PANWAR'}});
  await prisma.user.create({data:{firstName: 'NIHAR', lastName: 'MEHTA'}});
  await prisma.user.create({data:{firstName: 'PRADEEP', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'VINAY', lastName: 'RAI'}});
  await prisma.user.create({data:{firstName: 'SAIR', lastName: 'SAYED'}});
  await prisma.user.create({data:{firstName: 'DOUG', lastName: 'HEROLD'}});
  await prisma.user.create({data:{firstName: 'MATT', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'JEREMY', lastName: 'SCHROEDER'}});
  await prisma.user.create({data:{firstName: 'LUKE BIESANZ'}});
  await prisma.user.create({data:{firstName: 'MATTHEW SMITH'}});
  await prisma.user.create({data:{firstName: 'DANIEL J VINING'}});
  await prisma.user.create({data:{firstName: 'POOMATHI DURAISAMY'}});
  await prisma.user.create({data:{firstName: 'RON S BURLEY'}});
  await prisma.user.create({data:{firstName: 'JOSHUA TREPTOW'}});
  await prisma.user.create({data:{firstName: 'RYAN PETTYPOOL'}});
  await prisma.user.create({data:{firstName: 'FLOYD MILTZ'}});
  await prisma.user.create({data:{firstName: 'TONY HENIGAN'}});
  await prisma.user.create({data:{firstName: 'ALLAELDIN HASSAN'}});
  await prisma.user.create({data:{firstName: 'RONDA BARNES'}});
  await prisma.user.create({data:{firstName: 'MUZZAMIL KHAN'}});
  await prisma.user.create({data:{firstName: 'TY SLOFFER'}});
  await prisma.user.create({data:{firstName: 'BRANDON WALSH'}});
  await prisma.user.create({data:{firstName: 'HYUN JUNG'}});
  await prisma.user.create({data:{firstName: 'SURESH K HARIKRISHNAN'}});
  await prisma.user.create({data:{firstName: 'ALI X AYOUB'}});
  await prisma.user.create({data:{firstName: 'PONCHITO IGNACIO'}});
  await prisma.user.create({data:{firstName: 'JASON JACKSON'}});
  await prisma.user.create({data:{firstName: 'WILLIAM TIPTON'}});
  await prisma.user.create({data:{firstName: 'JAMES FERLAND'}});
  await prisma.user.create({data:{firstName: 'THOMAS NIEMANN'}});
  await prisma.user.create({data:{firstName: 'MANINDER GUJRAL'}});
  await prisma.user.create({data:{firstName: 'CLAUDE HETRICK'}});
  await prisma.user.create({data:{firstName: 'KERWIN MASTEN'}});
  await prisma.user.create({data:{firstName: 'Ertaz ISLAM'}});
  await prisma.user.create({data:{firstName: 'JALIL ARBABSHIRANI'}});
  await prisma.user.create({data:{firstName: 'SUBRAMANIAN RAMU'}});
  await prisma.user.create({data:{firstName: 'SHAWN ZAMIR'}});
  await prisma.user.create({data:{firstName: 'JIM M LATHAM'}});
  await prisma.user.create({data:{firstName: 'AMOR B SIMEON'}});
  await prisma.user.create({data:{firstName: 'MARK W MCCALLA'}});
  await prisma.user.create({data:{firstName: 'CARLA K JUNG'}});
  await prisma.user.create({data:{firstName: 'CATHERINE', lastName: 'ZHU'}});
  await prisma.user.create({data:{firstName: 'ENRICO', lastName: 'CORNEJO'}});
  await prisma.user.create({data:{firstName: 'CHRISTIAN', lastName: 'SUAREZ'}});
  await prisma.user.create({data:{firstName: 'Fariborz', lastName: 'Ahmadkhanlou'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'TUMILTY'}});
  await prisma.user.create({data:{firstName: 'TESFAY', lastName: 'SEBAHTU'}});
  await prisma.user.create({data:{firstName: 'DUSTIN', lastName: 'PHAM'}});
  await prisma.user.create({data:{firstName: 'JONATHAN', lastName: 'GILMORE'}});
  await prisma.user.create({data:{firstName: 'REGINALD', lastName: 'CLARKE JR'}});
  await prisma.user.create({data:{firstName: 'MICHAEL HEINIG'}});
  await prisma.user.create({data:{firstName: 'ARIEL CURA'}});
  await prisma.user.create({data:{firstName: 'JONATHAN KAISER'}});
  await prisma.user.create({data:{firstName: 'RAJARAJAN RAJENDRAN'}});
  await prisma.user.create({data:{firstName: 'MRIDUL CHATURVEDI'}});
  await prisma.user.create({data:{firstName: 'LYNDA NG'}});
  await prisma.user.create({data:{firstName: 'YUH-RYH LIANG'}});
  await prisma.user.create({data:{firstName: 'LAMSON DANG'}});
  await prisma.user.create({data:{firstName: 'HASSAN S ZAKI'}});
  await prisma.user.create({data:{firstName: 'MARCK GORSZWICK'}});
  await prisma.user.create({data:{firstName: 'PRIYA RAMANATHAN'}});
  await prisma.user.create({data:{firstName: 'HENRY LAU'}});
  await prisma.user.create({data:{firstName: 'GIDEON TELLA'}});
  await prisma.user.create({data:{firstName: 'GRADY IMEL'}});
  await prisma.user.create({data:{firstName: 'PRIYA X RAMANATHAN'}});
  await prisma.user.create({data:{firstName: 'VIJAY RUDRARAJU'}});
  await prisma.user.create({data:{firstName: 'SHAMANA DESAI'}});
  await prisma.user.create({data:{firstName: 'PAUL LOPEZ'}});
  await prisma.user.create({data:{firstName: 'MOHAMMAD SHOUQAT'}});
  await prisma.user.create({data:{firstName: 'YAIR DORY'}});
  await prisma.user.create({data:{firstName: 'MARYANNE M LOPEZ'}});
  await prisma.user.create({data:{firstName: 'BRUCE BURRIS'}});
  await prisma.user.create({data:{firstName: 'HARNEET S GILL'}});
  await prisma.user.create({data:{firstName: 'ANKUR NIGAM'}});
  await prisma.user.create({data:{firstName: 'PIO RAOUL N CASTRO'}});
  await prisma.user.create({data:{firstName: 'DREW MELBY'}});
  await prisma.user.create({data:{firstName: 'NAJEEB ZUBAIRI'}});
  await prisma.user.create({data:{firstName: 'SON BUI'}});
  await prisma.user.create({data:{firstName: 'DENNIS TELLEEN'}});
  await prisma.user.create({data:{firstName: 'MAYUR DESAI'}});
  await prisma.user.create({data:{firstName: 'MUDIT MOHAN GAUR'}});
  await prisma.user.create({data:{firstName: 'MOHAMED SHALTOT'}});
  await prisma.user.create({data:{firstName: 'LAURA STEFFLER'}});
  await prisma.user.create({data:{firstName: 'AFEWORK KASSAYE'}});
  await prisma.user.create({data:{firstName: 'VISHU X SRINIVASAMURTHY'}});
  await prisma.user.create({data:{firstName: 'GAURAV ANAND MATHUR'}});
  await prisma.user.create({data:{firstName: 'NAGA MUKTHA KONDA'}});
  await prisma.user.create({data:{firstName: 'ROSHAN', lastName: 'TAHERIAN'}});
  await prisma.user.create({data:{firstName: 'MICHAEL', lastName: 'CHANICKA'}});
  await prisma.user.create({data:{firstName: 'VENKATA', lastName: 'TEJA'}});
  await prisma.user.create({data:{firstName: 'ISHA', lastName: 'SATYAKAM'}});
  await prisma.user.create({data:{firstName: 'BIJOY', lastName: 'SKARIA'}});
  await prisma.user.create({data:{firstName: 'VIKAS', lastName: 'DEWANGAN'}});
  await prisma.user.create({data:{firstName: 'MANEESH', lastName: 'GAUR'}});
  await prisma.user.create({data:{firstName: 'HARISH RAMAMOORTHY'}});
  await prisma.user.create({data:{firstName: 'PRATEEK KHANNA'}});
  await prisma.user.create({data:{firstName: 'SOROUSH NASIRZADEH'}});
  await prisma.user.create({data:{firstName: 'JITENDRA ASATI'}});
  await prisma.user.create({data:{firstName: 'DEVESH RANGNEKAR'}});
  await prisma.user.create({data:{firstName: 'JEFFREY CARR'}});
  await prisma.user.create({data:{firstName: 'DINESH CHILAMAKURI'}});
  await prisma.user.create({data:{firstName: 'ROBERT BACKUS'}});
  await prisma.user.create({data:{firstName: 'WALID SABBAGH'}});
  await prisma.user.create({data:{firstName: 'HO NAMKUNG'}});
  await prisma.user.create({data:{firstName: 'KRISHNA P CHANDRADA'}});
  await prisma.user.create({data:{firstName: 'Mehdi Moghaddam'}});
  await prisma.user.create({data:{firstName: 'FOKRUL ALAM'}});
  await prisma.user.create({data:{firstName: 'SAY LO'}});
  await prisma.user.create({data:{firstName: 'MICHAEL J WATERMAN'}});
  await prisma.user.create({data:{firstName: 'VIRGINIA MACAALAY'}});
  await prisma.user.create({data:{firstName: 'DENNIS TRAN'}});
  await prisma.user.create({data:{firstName: 'ANUP KUMAR JHA'}});
  await prisma.user.create({data:{firstName: 'KONSTANTIN ILIEV'}});
  await prisma.user.create({data:{firstName: 'JEFFREY LAI'}});
  await prisma.user.create({data:{firstName: 'ASHISH KUMAR SHARMA'}});
  await prisma.user.create({data:{firstName: 'ASHISH CHUGH'}});
  await prisma.user.create({data:{firstName: 'MATTHEW WITT'}});
  await prisma.user.create({data:{firstName: 'Ivan Pham'}});
  await prisma.user.create({data:{firstName: 'SAKET KAPUR'}});
  await prisma.user.create({data:{firstName: 'HUGO BERNARDO'}});
  await prisma.user.create({data:{firstName: 'JOSEPH BARRON'}});
  await prisma.user.create({data:{firstName: 'JASON GINSBERG'}});
  await prisma.user.create({data:{firstName: 'STEVEN RADKE'}});
  await prisma.user.create({data:{firstName: 'ERIC WONG'}});
  await prisma.user.create({data:{firstName: 'KEITH BROOKING'}});
  await prisma.user.create({data:{firstName: 'RUI GUO'}});
  await prisma.user.create({data:{firstName: 'AMIT KUMAR SAGAR'}});
  await prisma.user.create({data:{firstName: 'GORDON GRAHAM'}});
  await prisma.user.create({data:{firstName: 'MANUEL ALBERT'}});
  await prisma.user.create({data:{firstName: 'NAV SINGH'}});
  await prisma.user.create({data:{firstName: 'KOYELI MAJUMDER'}});
  await prisma.user.create({data:{firstName: 'TELESPHORE B PEGNYEMB'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER DE POL'}});
  await prisma.user.create({data:{firstName: 'VIPUL X SHAH'}});
  await prisma.user.create({data:{firstName: 'ARIF MALIK'}});
  await prisma.user.create({data:{firstName: 'CESAR TANSENGCO'}});
  await prisma.user.create({data:{firstName: 'KAMRAN X KHURSHID'}});
  await prisma.user.create({data:{firstName: 'NAVEEN MAUDGAL'}});
  await prisma.user.create({data:{firstName: 'HUBER PENA'}});
  await prisma.user.create({data:{firstName: 'LEANDRO RECOVA'}});
  await prisma.user.create({data:{firstName: 'CRAIG J STANZIANO'}});
  await prisma.user.create({data:{firstName: 'NARAMSIN TAPEVERI'}});
  await prisma.user.create({data:{firstName: 'RUSSELL BELLAMY'}});
  await prisma.user.create({data:{firstName: 'RAYMOND', lastName: 'DIZON'}});
  await prisma.user.create({data:{firstName: 'RAKESH', lastName: 'J'}});
  await prisma.user.create({data:{firstName: 'EDWIN', lastName: 'JAVIER'}});
  await prisma.user.create({data:{firstName: 'KATHLEEN', lastName: 'ABOLA'}});
  await prisma.user.create({data:{firstName: 'FRANK', lastName: 'BUDIANTO'}});
  await prisma.user.create({data:{firstName: 'JEFF', lastName: 'BLUM'}});
  await prisma.user.create({data:{firstName: 'TARANG GOSALIA'}});
  await prisma.user.create({data:{firstName: 'BRYAN THACKWELL'}});
  await prisma.user.create({data:{firstName: 'DANNY HERNANDEZ'}});
  await prisma.user.create({data:{firstName: 'ZIAD K CHEIBAN'}});
  await prisma.user.create({data:{firstName: 'SWETA P IYER'}});
  await prisma.user.create({data:{firstName: 'LEIJIAN LIU'}});
  await prisma.user.create({data:{firstName: 'GAURAV KUMAR'}});
  await prisma.user.create({data:{firstName: 'TYRONE M JONES'}});
  await prisma.user.create({data:{firstName: 'VID ADIRAJU'}});
  await prisma.user.create({data:{firstName: 'ABDELLAH BENSALMIA'}});
  await prisma.user.create({data:{firstName: 'SIRISH MINAPALLI'}});
  await prisma.user.create({data:{firstName: 'PRIYA ROY'}});
  await prisma.user.create({data:{firstName: 'MANNY HARO'}});
  await prisma.user.create({data:{firstName: 'AMEYA RANADE'}});
  await prisma.user.create({data:{firstName: 'ANTHONY CAMAYA'}});
  await prisma.user.create({data:{firstName: 'FENG-SHIH KAO'}});
  await prisma.user.create({data:{firstName: 'JOHN L SULLIVAN'}});
  await prisma.user.create({data:{firstName: 'C RAJ KHANNA'}});
  await prisma.user.create({data:{firstName: 'AMOL BHOBE'}});
  await prisma.user.create({data:{firstName: 'AARON WIEBE'}});
  await prisma.user.create({data:{firstName: 'JOSH GERST'}});
  await prisma.user.create({data:{firstName: 'JAMES HO'}});
  await prisma.user.create({data:{firstName: 'TROY HOWARD BRYANT'}});
  await prisma.user.create({data:{firstName: 'PENUMATSA VARMA'}});
  await prisma.user.create({data:{firstName: 'DONNY X BUI'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER BRITT'}});
  await prisma.user.create({data:{firstName: 'AMIT BUTOLA'}});
  await prisma.user.create({data:{firstName: 'ADAM WAITE'}});
  await prisma.user.create({data:{firstName: 'ROB SVOBODA'}});
  await prisma.user.create({data:{firstName: 'ESSAM ALKHADRA'}});
  await prisma.user.create({data:{firstName: 'STEVE ZHU'}});
  await prisma.user.create({data:{firstName: 'DEL CALVERT'}});
  await prisma.user.create({data:{firstName: 'BRIAN CHAVEZ'}});
  await prisma.user.create({data:{firstName: 'STEVEN HOANG'}});
  await prisma.user.create({data:{firstName: 'MINGCHUN YANG'}});
  await prisma.user.create({data:{firstName: 'TUSHAR N SHAH'}});
  await prisma.user.create({data:{firstName: 'HENRY C HANCOCK'}});
  await prisma.user.create({data:{firstName: 'DOMINIC MARTINEZ'}});
  await prisma.user.create({data:{firstName: 'SHAFIUL LITU'}});
  await prisma.user.create({data:{firstName: 'JOSEF NAPULI'}});
  await prisma.user.create({data:{firstName: 'PANKAJ GOEL'}});
  await prisma.user.create({data:{firstName: 'NITIN BIROTE'}});
  await prisma.user.create({data:{firstName: 'GENE VOSKOBOYNIK'}});
  await prisma.user.create({data:{firstName: 'JOHNNY MENDOZA'}});
  await prisma.user.create({data:{firstName: 'SATINDER BHOGAL'}});
  await prisma.user.create({data:{firstName: 'LARRY T FAJARDO'}});
  await prisma.user.create({data:{firstName: 'Edward A Hsu'}});
  await prisma.user.create({data:{firstName: 'SANDHYA RUDRARAJU'}});
  await prisma.user.create({data:{firstName: 'SWATI BHARGAVA'}});
  await prisma.user.create({data:{firstName: 'GAURAV PARIKH'}});
  await prisma.user.create({data:{firstName: 'JATINDER'}});
  await prisma.user.create({data:{firstName: 'ANDREW CANOUN'}});
  await prisma.user.create({data:{firstName: 'JEFFREY JABLONSKI'}});
  await prisma.user.create({data:{firstName: 'JOHN LUDLOW'}});
  await prisma.user.create({data:{firstName: 'JASMINE FIGUEROA'}});
  await prisma.user.create({data:{firstName: 'JULIO HERNANDEZ'}});
  await prisma.user.create({data:{firstName: 'HEIDI PAYNE'}});
  await prisma.user.create({data:{firstName: 'RAFIQUR X RAHMAN'}});
  await prisma.user.create({data:{firstName: 'LISA BERGSHOLM'}});
  await prisma.user.create({data:{firstName: 'TENG COMPANIA'}});
  await prisma.user.create({data:{firstName: 'CAROLYN TANN'}});
  await prisma.user.create({data:{firstName: 'RENE VALLADARES'}});
  await prisma.user.create({data:{firstName: 'VU ANH TRAN'}});
  await prisma.user.create({data:{firstName: 'FALAH CHEBBO'}});
  await prisma.user.create({data:{firstName: 'SYED R ZAIDI'}});
  await prisma.user.create({data:{firstName: 'JASPAL SINGH'}});
  await prisma.user.create({data:{firstName: 'ALAN J FALK'}});
  await prisma.user.create({data:{firstName: 'KITTANON MARTIN'}});
  await prisma.user.create({data:{firstName: 'REDFORD CRUZ'}});
  await prisma.user.create({data:{firstName: 'SUNIL SUDHAKARAN'}});
  await prisma.user.create({data:{firstName: 'LORI FOX'}});
  await prisma.user.create({data:{firstName: 'JEREMY MAROTTE'}});
  await prisma.user.create({data:{firstName: 'MICHAEL D DOWNS'}});
  await prisma.user.create({data:{firstName: 'ROBERT PHEASANT'}});
  await prisma.user.create({data:{firstName: 'JEFF BARRETT'}});
  await prisma.user.create({data:{firstName: 'ANDREW A CARTER'}});
  await prisma.user.create({data:{firstName: 'TOSHA LARKIN'}});
  await prisma.user.create({data:{firstName: 'CRAIG LICKLIDER'}});
  await prisma.user.create({data:{firstName: 'IGOR ZHBANKOV'}});
  await prisma.user.create({data:{firstName: 'JOHN BORJAS'}});
  await prisma.user.create({data:{firstName: 'MANDEEP SINGH TANWAR'}});
  await prisma.user.create({data:{firstName: 'VANCE MOSSER'}});
  await prisma.user.create({data:{firstName: 'TUAN TU'}});
  await prisma.user.create({data:{firstName: 'VIVEK', lastName: 'BARNWAL'}});
  await prisma.user.create({data:{firstName: 'JYOTI', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'DONNY', lastName: 'BROWN'}});
  await prisma.user.create({data:{firstName: 'JIM', lastName: 'LATHAM'}});
  await prisma.user.create({data:{firstName: 'PAUL', lastName: 'FISCHER'}});
  await prisma.user.create({data:{firstName: 'DAMANJIT', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'KORDOWSKI '}});
  await prisma.user.create({data:{firstName: 'MEGHNA', lastName: 'GANDHI'}});
  await prisma.user.create({data:{firstName: 'THOMAS', lastName: 'TSIGE'}});
  await prisma.user.create({data:{firstName: 'PRIYANKA', lastName: 'SHARMA'}});
  await prisma.user.create({data:{firstName: 'PRASHANT', lastName: 'KUMAR'}});
  await prisma.user.create({data:{firstName: 'GREGORY', lastName: 'THOMAS'}});
  await prisma.user.create({data:{firstName: 'SUE', lastName: 'BERGER'}});
  await prisma.user.create({data:{firstName: 'MATTHEW', lastName: 'RIGNEY'}});
  await prisma.user.create({data:{firstName: 'MARIA', lastName: 'KUTI'}});
  await prisma.user.create({data:{firstName: 'MARK', lastName: 'GLAMM'}});
  await prisma.user.create({data:{firstName: 'RENEE', lastName: 'CRIDER'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'FANNIN'}});
  await prisma.user.create({data:{firstName: 'KELVIN', lastName: 'AVNUKOV'}});
  await prisma.user.create({data:{firstName: 'SHADI', lastName: 'FARASIN'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'HANNA'}});
  await prisma.user.create({data:{firstName: 'RONALD', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'DUTTON'}});
  await prisma.user.create({data:{firstName: 'JOSEPH', lastName: 'LATTANZIO'}});
  await prisma.user.create({data:{firstName: 'DHANASHREE', lastName: 'BHANDARI'}});
  await prisma.user.create({data:{firstName: 'SYED', lastName: 'NABEEL'}});
  await prisma.user.create({data:{firstName: 'LAWRENCE', lastName: 'CARLISLE'}});
  await prisma.user.create({data:{firstName: 'JOSEPH', lastName: 'JOYCE'}});
  await prisma.user.create({data:{firstName: 'HEATHER', lastName: 'GAEBELEIN'}});
  await prisma.user.create({data:{firstName: 'BETH', lastName: 'SYRVALIN'}});
  await prisma.user.create({data:{firstName: 'RAYMOND', lastName: 'YU'}});
  await prisma.user.create({data:{firstName: 'KAI', lastName: 'SOKSO'}});
  await prisma.user.create({data:{firstName: 'ANNA', lastName: 'LINGAR'}});
  await prisma.user.create({data:{firstName: 'ED', lastName: 'POWELL'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'JAHR'}});
  await prisma.user.create({data:{firstName: 'TAREKE', lastName: 'TUKU'}});
  await prisma.user.create({data:{firstName: 'KRAIG', lastName: 'CLARK'}});
  await prisma.user.create({data:{firstName: 'PRAVEEN', lastName: 'YADAV'}});
  await prisma.user.create({data:{firstName: 'SATISH', lastName: 'KOLLI'}});
  await prisma.user.create({data:{firstName: 'DASON', lastName: 'RAPP'}});
  await prisma.user.create({data:{firstName: 'GARY', lastName: 'VAUGHAN'}});
  await prisma.user.create({data:{firstName: 'BIN', lastName: 'MATIOS'}});
  await prisma.user.create({data:{firstName: 'SALAHUDDIN', lastName: 'SHAHZAD'}});
  await prisma.user.create({data:{firstName: 'B', lastName: 'SCHNEIDER'}});
  await prisma.user.create({data:{firstName: 'GIRMA', lastName: 'YILMA'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'BREWER'}});
  await prisma.user.create({data:{firstName: 'GREG', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'HRIDAY', lastName: 'DESAI'}});
  await prisma.user.create({data:{firstName: 'ELADIO', lastName: 'GANDARA'}});
  await prisma.user.create({data:{firstName: 'NICK', lastName: 'DOYLE'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'KLANECKY'}});
  await prisma.user.create({data:{firstName: 'SAKOL', lastName: 'ORTIZ'}});
  await prisma.user.create({data:{firstName: 'STEVE', lastName: 'DECHO'}});
  await prisma.user.create({data:{firstName: 'JEFF', lastName: 'DECK'}});
  await prisma.user.create({data:{firstName: 'SERGEY', lastName: 'OLEYNIK'}});
  await prisma.user.create({data:{firstName: 'GABRIEL', lastName: 'POLING'}});
  await prisma.user.create({data:{firstName: 'CARSON', lastName: 'SMITH'}});
  await prisma.user.create({data:{firstName: 'JEREMY', lastName: 'GILBERT'}});
  await prisma.user.create({data:{firstName: 'MIKE', lastName: 'DUNN'}});
  await prisma.user.create({data:{firstName: 'CURT', lastName: 'KABRIS'}});
  await prisma.user.create({data:{firstName: 'JASON', lastName: 'KLEINEMAS'}});
  await prisma.user.create({data:{firstName: 'DUSTIN', lastName: 'LOZINSKI'}});
  await prisma.user.create({data:{firstName: 'SANTOSH', lastName: 'YADAV'}});
  await prisma.user.create({data:{firstName: 'RACHAN', lastName: 'HR'}});
  await prisma.user.create({data:{firstName: 'ANKUSH', lastName: 'BANSAL'}});
  await prisma.user.create({data:{firstName: 'MONAL', lastName: 'NRIMANJAA'}});
  await prisma.user.create({data:{firstName: 'RONALD', lastName: 'COOK'}});
  await prisma.user.create({data:{firstName: 'RODNEY', lastName: 'BIEAK'}});
  await prisma.user.create({data:{firstName: 'RAMESH', lastName: 'KUMAR'}});
  await prisma.user.create({data:{firstName: 'PAWAN', lastName: 'KEWALRAMANI'}});
  await prisma.user.create({data:{firstName: 'MOHAMAD', lastName: 'BULBUL'}});
  await prisma.user.create({data:{firstName: 'BRAD', lastName: 'KELLY'}});
  await prisma.user.create({data:{firstName: 'WILLIAM', lastName: 'CIUFFO'}});
  await prisma.user.create({data:{firstName: 'VISHA', lastName: 'KHOSLA'}});
  await prisma.user.create({data:{firstName: 'THEODORE', lastName: 'MCCLEARY'}});
  await prisma.user.create({data:{firstName: 'KENNETH', lastName: 'TSANG'}});
  await prisma.user.create({data:{firstName: 'AVINASH', lastName: 'HARIKRISHNAN'}});
  await prisma.user.create({data:{firstName: 'ARUN', lastName: 'RAMASUBRAHMAYAN'}});
  await prisma.user.create({data:{firstName: 'CLEMENT POOLE'}});
  await prisma.user.create({data:{firstName: 'NEIL NOCETE'}});
  await prisma.user.create({data:{firstName: 'JEAN-PIERRE PETO'}});
  await prisma.user.create({data:{firstName: 'LAEL LORUSSO'}});
  await prisma.user.create({data:{firstName: 'FRANK PUCHINO'}});
  await prisma.user.create({data:{firstName: 'FATHI ZEKARIA'}});
  await prisma.user.create({data:{firstName: 'RICHARD C FISCHR'}});
  await prisma.user.create({data:{firstName: 'LELAND BROWN'}});
  await prisma.user.create({data:{firstName: 'ARCHIT JAIN'}});
  await prisma.user.create({data:{firstName: 'CHRIS RADLEY'}});
  await prisma.user.create({data:{firstName: 'RHABIGAIL HERNANDEZ'}});
  await prisma.user.create({data:{firstName: 'TUNG VU'}});
  await prisma.user.create({data:{firstName: 'ROSARIO CONELLI'}});
  await prisma.user.create({data:{firstName: 'MOHD FARHAN'}});
  await prisma.user.create({data:{firstName: 'TRISHA ESLICK-DAVIS'}});
  await prisma.user.create({data:{firstName: 'ANIL SINGHA'}});
  await prisma.user.create({data:{firstName: 'RICHA UPADHYAY'}});
  await prisma.user.create({data:{firstName: 'DARREN RUZICKA'}});
  await prisma.user.create({data:{firstName: 'NIPU BAKHTYAR'}});
  await prisma.user.create({data:{firstName: 'RAED ABULIBDEH'}});
  await prisma.user.create({data:{firstName: 'MOHIT SETHI'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER WILSON'}});
  await prisma.user.create({data:{firstName: 'RAY O FOUGHT'}});
  await prisma.user.create({data:{firstName: 'PAUL POTTS'}});
  await prisma.user.create({data:{firstName: 'CHAD DAGENHARDT'}});
  await prisma.user.create({data:{firstName: 'IFTEKHAR HASAN'}});
  await prisma.user.create({data:{firstName: 'ANDREW.MAYES'}});
  await prisma.user.create({data:{firstName: 'CAROLYN FUJIOKA'}});
  await prisma.user.create({data:{firstName: 'BADARINATH KIDAMBI'}});
  await prisma.user.create({data:{firstName: 'FONG LO'}});
  await prisma.user.create({data:{firstName: 'KISHOR PALVE'}});
  await prisma.user.create({data:{firstName: 'MIKEL NAKAMOTO'}});
  await prisma.user.create({data:{firstName: 'EASWAR PRASAD'}});
  await prisma.user.create({data:{firstName: 'ASHISH KUMAR AGRAWAL'}});
  await prisma.user.create({data:{firstName: 'SUJIT.KUMAR'}});
  await prisma.user.create({data:{firstName: 'SUKHDEV ANANDA PAWAR'}});
  await prisma.user.create({data:{firstName: 'NEHA  GUPTA'}});
  await prisma.user.create({data:{firstName: 'ANDREW MAYES'}});
  await prisma.user.create({data:{firstName: 'DONNA VALIENTE'}});
  await prisma.user.create({data:{firstName: 'WILLIAM MADDEN'}});
  await prisma.user.create({data:{firstName: 'ADAM RILEY'}});
  await prisma.user.create({data:{firstName: 'SEAN HELINE'}});
  await prisma.user.create({data:{firstName: 'GARY WILD'}});
  await prisma.user.create({data:{firstName: 'NIKHIL MALI'}});
  await prisma.user.create({data:{firstName: 'MINESH SHETH'}});
  await prisma.user.create({data:{firstName: 'ASHUTOSH CHAUHAN'}});
  await prisma.user.create({data:{firstName: 'AMANDEEP C'}});
  await prisma.user.create({data:{firstName: 'MUKESH KUMAR'}});
  await prisma.user.create({data:{firstName: 'ABHISHEK SOOD'}});
  await prisma.user.create({data:{firstName: 'AJITHA KUMAR'}});
  await prisma.user.create({data:{firstName: 'DAWANJEET.SINGH.BEDI'}});
  await prisma.user.create({data:{firstName: 'RAVISH', lastName: 'GUPTA'}});
  await prisma.user.create({data:{firstName: 'ABHISHEK', lastName: 'SINGH'}});
  await prisma.user.create({data:{firstName: 'NATALIE', lastName: 'NOEL'}});
  await prisma.user.create({data:{firstName: 'MING', lastName: 'CHAN'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'KLOTSOS'}});
  await prisma.user.create({data:{firstName: 'TONY', lastName: 'LAM'}});
  await prisma.user.create({data:{firstName: 'ABHIJIT', lastName: 'BANDIVDEKAR'}});
  await prisma.user.create({data:{firstName: 'SHAHID', lastName: 'KAGAL'}});
  await prisma.user.create({data:{firstName: 'OMAR', lastName: 'DELGADO'}});
  await prisma.user.create({data:{firstName: 'DOMINADOR', lastName: 'GALICINAO'}});
  await prisma.user.create({data:{firstName: 'SHAHRAM', lastName: 'MAHKU'}});
  await prisma.user.create({data:{firstName: 'LUCIO', lastName: 'ROMERO'}});
  await prisma.user.create({data:{firstName: 'RITABRATA', lastName: 'ROY'}});
  await prisma.user.create({data:{firstName: 'ASHWINI', lastName: 'KADABA'}});
  await prisma.user.create({data:{firstName: 'VARUN KUMAR NARASIMHE GOWDA'}});
  await prisma.user.create({data:{firstName: 'ARTHUR THOMPSON'}});
  await prisma.user.create({data:{firstName: 'KRISHNA KUMAR'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER A CASSELES'}});
  await prisma.user.create({data:{firstName: 'MICHAEL LITTMAN'}});
  await prisma.user.create({data:{firstName: 'ROBERT BERTONA'}});
  await prisma.user.create({data:{firstName: 'ANUJ DUTIA'}});
  await prisma.user.create({data:{firstName: 'NAMIT SHARMA'}});
  await prisma.user.create({data:{firstName: 'RICHARD SCHARP'}});
  await prisma.user.create({data:{firstName: 'GARIMA UPADHYAYA'}});
  await prisma.user.create({data:{firstName: 'DHEERAJ GUPTA'}});
  await prisma.user.create({data:{firstName: 'SEAN REID'}});
  await prisma.user.create({data:{firstName: 'NOOSHIN ZAREIAN'}});
  await prisma.user.create({data:{firstName: 'SOUFIANE TOURY'}});
  await prisma.user.create({data:{firstName: 'FRANCES BOSCHULTE'}});
  await prisma.user.create({data:{firstName: 'VISHAL MODY'}});
  await prisma.user.create({data:{firstName: 'ARUN GUPTA'}});
  await prisma.user.create({data:{firstName: 'EDUARDO ORELLANA'}});
  await prisma.user.create({data:{firstName: 'EDWIN S ORTEGA'}});
  await prisma.user.create({data:{firstName: 'GOVINDARAJKUMAR S MAKHIJA'}});
  await prisma.user.create({data:{firstName: 'ALKESH AMIN'}});
  await prisma.user.create({data:{firstName: 'Jimmy XU'}});
  await prisma.user.create({data:{firstName: 'SHAHID X MIRZA'}});
  await prisma.user.create({data:{firstName: 'NIHAR SHAH'}});
  await prisma.user.create({data:{firstName: 'JIM PROCIW'}});
  await prisma.user.create({data:{firstName: 'WELLINGTON SIBULO'}});
  await prisma.user.create({data:{firstName: 'RICHARD DREESE'}});
  await prisma.user.create({data:{firstName: 'FRANK ZHANG'}});
  await prisma.user.create({data:{firstName: 'RAHIM LAMKHIDDA'}});
  await prisma.user.create({data:{firstName: 'PASCAL'}});
  await prisma.user.create({data:{firstName: 'MUSTAFA X BAKHTYAR'}});
  await prisma.user.create({data:{firstName: 'MIKE TOLBERT'}});
  await prisma.user.create({data:{firstName: 'BRENDEN WEEKS'}});
  await prisma.user.create({data:{firstName: 'LEANN NGUYEN'}});
  await prisma.user.create({data:{firstName: 'MICHAEL HENDERSON'}});
  await prisma.user.create({data:{firstName: 'BRYAN DEVARY'}});
  await prisma.user.create({data:{firstName: 'JASPER L HOLMES'}});
  await prisma.user.create({data:{firstName: 'ANANTH PARIMI'}});
  await prisma.user.create({data:{firstName: 'CRAIG RODRIGUEZ'}});
  await prisma.user.create({data:{firstName: 'DAVE WILTSHIRE'}});
  await prisma.user.create({data:{firstName: 'MARK BUNNELL'}});
  await prisma.user.create({data:{firstName: 'MICHELLE PINTO'}});
  await prisma.user.create({data:{firstName: 'DAVE WALTERS'}});
  await prisma.user.create({data:{firstName: 'JOSEPH SPITZ'}});
  await prisma.user.create({data:{firstName: 'EDGARDO DIMAGIBA'}});
  await prisma.user.create({data:{firstName: 'LAARNICHRISTINE J BUGAYONG'}});
  await prisma.user.create({data:{firstName: 'JUANITO CARRASCO'}});
  await prisma.user.create({data:{firstName: 'QI ZHANG'}});
  await prisma.user.create({data:{firstName: 'STEVEN   VITULLI'}});
  await prisma.user.create({data:{firstName: 'JAMES T MADISON'}});
  await prisma.user.create({data:{firstName: 'ADAM L WHITE'}});
  await prisma.user.create({data:{firstName: 'ELIZABETH RASOUL'}});
  await prisma.user.create({data:{firstName: 'RYAN HARSONO'}});
  await prisma.user.create({data:{firstName: 'RICHARD SULLIVAN'}});
  await prisma.user.create({data:{firstName: 'MATT KOUGH'}});
  await prisma.user.create({data:{firstName: 'MICHAEL HOBSON'}});
  await prisma.user.create({data:{firstName: 'THOMAS RYAN'}});
  await prisma.user.create({data:{firstName: 'CHARLES HOCKLEY'}});
  await prisma.user.create({data:{firstName: 'GREGORY TODD'}});
  await prisma.user.create({data:{firstName: 'KONARK KHURANA'}});
  await prisma.user.create({data:{firstName: 'STEVEN J VITULLI'}});
  await prisma.user.create({data:{firstName: 'ANNA XIONG'}});
  await prisma.user.create({data:{firstName: 'FAOUZI ZEINEDDINE'}});
  await prisma.user.create({data:{firstName: 'DONI YURGANDONO'}});
  await prisma.user.create({data:{firstName: 'FOTIS KARAKATSOULIS'}});
  await prisma.user.create({data:{firstName: 'TERRANCE KOLODY'}});
  await prisma.user.create({data:{firstName: 'LAWRENCE EADIE'}});
  await prisma.user.create({data:{firstName: 'JONATHAN SABLAN'}});
  await prisma.user.create({data:{firstName: 'MICHEL ANTONESCO'}});
  await prisma.user.create({data:{firstName: 'AJAY GHANEKAR'}});
  await prisma.user.create({data:{firstName: 'KALEEM K KHAN'}});
  await prisma.user.create({data:{firstName: 'MOBIN M SHAIKH'}});
  await prisma.user.create({data:{firstName: 'FERNANDO CARRANZA'}});
  await prisma.user.create({data:{firstName: 'ARMOND NICKNOM'}});
  await prisma.user.create({data:{firstName: 'LEIGHTON TONG'}});
  await prisma.user.create({data:{firstName: 'TOM AVAKIAN'}});
  await prisma.user.create({data:{firstName: 'DEBORAH ROBINSON'}});
  await prisma.user.create({data:{firstName: 'Lance', lastName: 'Lukens'}});
  await prisma.user.create({data:{firstName: 'KOUSHAL', lastName: 'KESHRI'}});
  await prisma.user.create({data:{firstName: 'RASHID KHAN'}});
  await prisma.user.create({data:{firstName: 'SAFWAT HELMY'}});
  await prisma.user.create({data:{firstName: 'NAGESH NAYAK'}});
  await prisma.user.create({data:{firstName: 'FREDERICK RELYEA'}});
  await prisma.user.create({data:{firstName: 'RALPH MASTRANGELO'}});
  await prisma.user.create({data:{firstName: 'BRIAN SEDGWICK'}});
  await prisma.user.create({data:{firstName: 'ANUJ GUPTA'}});
  await prisma.user.create({data:{firstName: 'SACHIN LUTHRA'}});
  await prisma.user.create({data:{firstName: 'CHRIS BRIDENBAUGH'}});
  await prisma.user.create({data:{firstName: 'ARTHUR CAPWELL'}});
  await prisma.user.create({data:{firstName: 'SHIYAM SIVAGURUNATHAN'}});
  await prisma.user.create({data:{firstName: 'MICHAEL HUBER'}});
  await prisma.user.create({data:{firstName: 'ABHISHEK T TIWARI'}});
  await prisma.user.create({data:{firstName: 'JONATHAN EDWARDS'}});
  await prisma.user.create({data:{firstName: 'TIM DOLAN'}});
  await prisma.user.create({data:{firstName: 'PANKAJ.SABHLOCK'}});
  await prisma.user.create({data:{firstName: 'BEN FLOYD'}});
  await prisma.user.create({data:{firstName: 'ANTHONY J TRICOCI'}});
  await prisma.user.create({data:{firstName: 'CHARLES FERGUS'}});
  await prisma.user.create({data:{firstName: 'RIGOBERTO FLORES'}});
  await prisma.user.create({data:{firstName: 'PREET KANWAL KAUR'}});
  await prisma.user.create({data:{firstName: 'ALMA GLINOGA'}});
  await prisma.user.create({data:{firstName: 'JAMES MADISON'}});
  await prisma.user.create({data:{firstName: 'Ahmadou Sock'}});
  await prisma.user.create({data:{firstName: 'DJ KILIAN'}});
  await prisma.user.create({data:{firstName: 'NURDEEN LAWAL'}});
  await prisma.user.create({data:{firstName: 'BEN SHAPIRO'}});
  await prisma.user.create({data:{firstName: 'MATTHEW HEWITT'}});
  await prisma.user.create({data:{firstName: 'SATINDERBIR SINGH'}});
  await prisma.user.create({data:{firstName: 'LEHI MONTIERTH'}});
  await prisma.user.create({data:{firstName: 'RINA MHATRE'}});
  await prisma.user.create({data:{firstName: 'ANAND MEHROTRA'}});
  await prisma.user.create({data:{firstName: 'ALEX BELL'}});
  await prisma.user.create({data:{firstName: 'DAVE KNAPPERT'}});
  await prisma.user.create({data:{firstName: 'KAMAL DOSHI'}});
  await prisma.user.create({data:{firstName: 'PETER HUBBARD'}});
  await prisma.user.create({data:{firstName: 'JIM PANTANO'}});
  await prisma.user.create({data:{firstName: 'RICHARD KANE'}});
  await prisma.user.create({data:{firstName: 'MUSTAFA CICEK'}});
  await prisma.user.create({data:{firstName: 'PAUL SERRILLI'}});
  await prisma.user.create({data:{firstName: 'TAMBA KORTEQUEE'}});
  await prisma.user.create({data:{firstName: 'MICHAEL PIESON'}});
  await prisma.user.create({data:{firstName: 'SAEL A BOGA'}});
  await prisma.user.create({data:{firstName: 'DELL SLAUGHTER'}});
  await prisma.user.create({data:{firstName: 'SANGAM KUMAR SINGH'}});
  await prisma.user.create({data:{firstName: 'MOAZZEM HOSSAIN'}});
  await prisma.user.create({data:{firstName: 'BRIAN KARR'}});
  await prisma.user.create({data:{firstName: 'TEMPLE L JONES'}});
  await prisma.user.create({data:{firstName: 'JAMES L HIGGINS'}});
  await prisma.user.create({data:{firstName: 'RODERICK S SANTIAGO'}});
  await prisma.user.create({data:{firstName: 'BILL H VAUGHN'}});
  await prisma.user.create({data:{firstName: 'VALENCIA BAKER-WARD'}});
  await prisma.user.create({data:{firstName: 'LEATON JENKINS'}});
  await prisma.user.create({data:{firstName: 'WILLIAM H CARD'}});
  await prisma.user.create({data:{firstName: 'RICHARD GRESS'}});
  await prisma.user.create({data:{firstName: 'DAVID M CASTANEDA'}});
  await prisma.user.create({data:{firstName: 'SARANG LADDA'}});
  await prisma.user.create({data:{firstName: 'DAVID CASTANEDA'}});
  await prisma.user.create({data:{firstName: 'DAVID QUINLAN'}});
  await prisma.user.create({data:{firstName: 'HUMAN RAHMANIAN'}});
  await prisma.user.create({data:{firstName: 'BRETT LAWLESS'}});
  await prisma.user.create({data:{firstName: 'MICHAEL CASEY'}});
  await prisma.user.create({data:{firstName: 'GARY WESTER'}});
  await prisma.user.create({data:{firstName: 'MIKE', lastName: 'EDGE'}});
  await prisma.user.create({data:{firstName: 'Ramin', lastName: 'Badii'}});
  await prisma.user.create({data:{firstName: 'ADE', lastName: 'ZULFIKAR'}});
  await prisma.user.create({data:{firstName: 'PAUL', lastName: 'SCOTT'}});
  await prisma.user.create({data:{firstName: 'DANIEL', lastName: 'URIE'}});
  await prisma.user.create({data:{firstName: 'FARIBORZ', lastName: 'AHMADKHANLOU'}});
  await prisma.user.create({data:{firstName: 'MIKE', lastName: 'PAK'}});
  await prisma.user.create({data:{firstName: 'KEVIN FARR'}});
  await prisma.user.create({data:{firstName: 'MITAL SHAH'}});
  await prisma.user.create({data:{firstName: 'SIKSHA X BHATIA'}});
  await prisma.user.create({data:{firstName: 'ROSHAN ROY'}});
  await prisma.user.create({data:{firstName: 'MICHAEL RAFFA'}});
  await prisma.user.create({data:{firstName: 'ADITYA X KUMAR'}});
  await prisma.user.create({data:{firstName: 'JOHN PACLIK'}});
  await prisma.user.create({data:{firstName: 'RICHARD MAZZEO'}});
  await prisma.user.create({data:{firstName: 'BRYAN GREBIS'}});
  await prisma.user.create({data:{firstName: 'THOMAS GOLAS'}});
  await prisma.user.create({data:{firstName: 'MANAS PANDA'}});
  await prisma.user.create({data:{firstName: 'TIM HUYNH'}});
  await prisma.user.create({data:{firstName: 'UDAYAN'}});
  await prisma.user.create({data:{firstName: 'MICHELANGELO', lastName: 'CASTIGLIA'}});
  await prisma.user.create({data:{firstName: 'ARUNODAY BHATTACHARYA'}});
  await prisma.user.create({data:{firstName: 'RICHARD QUINTANA'}});
  await prisma.user.create({data:{firstName: 'WAYNE C SCHROEDER'}});
  await prisma.user.create({data:{firstName: 'FASIHA REHMAN'}});
  await prisma.user.create({data:{firstName: 'FRANK MENTO'}});
  await prisma.user.create({data:{firstName: 'MIKE ELLINIKOS'}});
  await prisma.user.create({data:{firstName: 'MANISH IDNANI'}});
  await prisma.user.create({data:{firstName: 'SHARIQ ASHFAQ'}});
  await prisma.user.create({data:{firstName: 'KRISHNA THUNGA'}});
  await prisma.user.create({data:{firstName: 'DINESH BHUTANI'}});
  await prisma.user.create({data:{firstName: 'ANGEL A ANDRADE'}});
  await prisma.user.create({data:{firstName: 'PANUPONG SRIAUTHARAWONG'}});
  await prisma.user.create({data:{firstName: 'LOI', lastName: 'VU'}});
  await prisma.user.create({data:{firstName: 'THANDAVA K THUNGA'}});
  await prisma.user.create({data:{firstName: 'AZEEM AHMAD'}});
  await prisma.user.create({data:{firstName: 'GLENN D PIERSON'}});
  await prisma.user.create({data:{firstName: 'WILLIAM ONEILL'}});
  await prisma.user.create({data:{firstName: 'AMIR R ABTAHI'}});
  await prisma.user.create({data:{firstName: 'DEEPAK GUPTA'}});
  await prisma.user.create({data:{firstName: 'YOGESH IYER'}});
  await prisma.user.create({data:{firstName: 'JOANN GUERRA'}});
  await prisma.user.create({data:{firstName: 'VISHAL KATARIA'}});
  await prisma.user.create({data:{firstName: 'RHOAN GORDON'}});
  await prisma.user.create({data:{firstName: 'CHIRNAV MASTER'}});
  await prisma.user.create({data:{firstName: 'Bassem Iskander'}});
  await prisma.user.create({data:{firstName: 'JONATHAN GO'}});
  await prisma.user.create({data:{firstName: 'RON EVANS'}});
  await prisma.user.create({data:{firstName: 'MANOJ X KUMAR'}});
  await prisma.user.create({data:{firstName: 'LEONID GOLONESKY'}});
  await prisma.user.create({data:{firstName: 'JOSEPH X MENIO'}});
  await prisma.user.create({data:{firstName: 'JIMMY T BRYANT'}});
  await prisma.user.create({data:{firstName: 'RICHARD X HILL'}});
  await prisma.user.create({data:{firstName: 'MAHDURA BHOGATE'}});
  await prisma.user.create({data:{firstName: 'VIPULANSH  SHARMA'}});
  await prisma.user.create({data:{firstName: 'NIKHIL SHARAD JADHAV'}});
  await prisma.user.create({data:{firstName: 'DEEPAK KUMAR MATTOO'}});
  await prisma.user.create({data:{firstName: 'BHAVIK JAIN'}});
  await prisma.user.create({data:{firstName: 'MUSTAFA ABDULLAH'}});
  await prisma.user.create({data:{firstName: 'HUSSAIN ZAHEER'}});
  await prisma.user.create({data:{firstName: 'ROBIN MCCOY'}});
  await prisma.user.create({data:{firstName: 'XUE WANG'}});
  await prisma.user.create({data:{firstName: 'RANJAN FERNANDO'}});
  await prisma.user.create({data:{firstName: 'STACY X CURRY'}});
  await prisma.user.create({data:{firstName: 'DEAN WATANABE'}});
  await prisma.user.create({data:{firstName: 'RAUL TORRES'}});
  await prisma.user.create({data:{firstName: 'MARIA PERALTA'}});
  await prisma.user.create({data:{firstName: 'CHI VAN'}});
  await prisma.user.create({data:{firstName: 'DRAGISA MILETIC'}});
  await prisma.user.create({data:{firstName: 'GARY O JOHNSTON'}});
  await prisma.user.create({data:{firstName: 'ALMA SWAIN'}});
  await prisma.user.create({data:{firstName: 'FOUAD BOUMAKH'}});
  await prisma.user.create({data:{firstName: 'MICHAEL F SEALS'}});
  await prisma.user.create({data:{firstName: 'MICHAEL ROTH'}});
  await prisma.user.create({data:{firstName: 'JAIME MOTA'}});
  await prisma.user.create({data:{firstName: 'JOSEPH JONES'}});
  await prisma.user.create({data:{firstName: 'JOHN R LUTE'}});
  await prisma.user.create({data:{firstName: 'MANISH G CHOPRA'}});
  await prisma.user.create({data:{firstName: 'ANDRES MENDOZA'}});
  await prisma.user.create({data:{firstName: 'MUKUL AWASTHI'}});
  await prisma.user.create({data:{firstName: 'MUTHUKUMARASWAMY SEKAR'}});
  await prisma.user.create({data:{firstName: 'PHUC PHAN'}});
  await prisma.user.create({data:{firstName: 'RIZWAN MUZAFFAR'}});
  await prisma.user.create({data:{firstName: 'DIEGO FRANCO'}});
  await prisma.user.create({data:{firstName: 'TAMI NGUYEN'}});
  await prisma.user.create({data:{firstName: 'TIM M AINSWORTH'}});
  await prisma.user.create({data:{firstName: 'THOMAS BESSER'}});
  await prisma.user.create({data:{firstName: 'JOHN DAVILLIER'}});
  await prisma.user.create({data:{firstName: 'ROBERT', lastName: 'MEYERS JR'}});
  await prisma.user.create({data:{firstName: 'CHRIS', lastName: 'HEYL'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'SAWYERS'}});
  await prisma.user.create({data:{firstName: 'RUSS CHRISMAN'}});
  await prisma.user.create({data:{firstName: 'DAN BYE'}});
  await prisma.user.create({data:{firstName: 'RANAJIT TRIPATHY'}});
  await prisma.user.create({data:{firstName: 'MANISHA PHULORIA '}});
  await prisma.user.create({data:{firstName: 'AMY KIDWELl'}});
  await prisma.user.create({data:{firstName: 'JEFF TOMLIN'}});
  await prisma.user.create({data:{firstName: 'DAN VREELAND'}});
  await prisma.user.create({data:{firstName: 'JACOB ZIPPRICH'}});
  await prisma.user.create({data:{firstName: 'ABHISHEK N. MISHRA'}});
  await prisma.user.create({data:{firstName: 'JAMES WOOLFOLK'}});
  await prisma.user.create({data:{firstName: 'OLIVER FEIBEL'}});
  await prisma.user.create({data:{firstName: 'SHELLI MUELLER'}});
  await prisma.user.create({data:{firstName: 'MATT MORIAN'}});
  await prisma.user.create({data:{firstName: 'ROMMEL YAZON'}});
  await prisma.user.create({data:{firstName: 'KIP BYNUM'}});
  await prisma.user.create({data:{firstName: 'PEGGY LAM'}});
  await prisma.user.create({data:{firstName: 'SURAJ KUMAR JHa'}});
  await prisma.user.create({data:{firstName: 'ANIL KUMAR MALVIYA'}});
  await prisma.user.create({data:{firstName: 'KEVIN REARDON'}});
  await prisma.user.create({data:{firstName: 'ABHIJIT PATHAK'}});
  await prisma.user.create({data:{firstName: 'LEO SMITH'}});
  await prisma.user.create({data:{firstName: 'BHANU', lastName: 'KAKARLA'}});
  await prisma.user.create({data:{firstName: 'RICHARD A BEAMAN'}});
  await prisma.user.create({data:{firstName: 'CRAIG QUEEN'}});
  await prisma.user.create({data:{firstName: 'NOEL HANSEN'}});
  await prisma.user.create({data:{firstName: 'NANCY A ', lastName: 'CLARK-BREIDENSTEIN'}});
  await prisma.user.create({data:{firstName: 'GENE EVANS'}});
  await prisma.user.create({data:{firstName: 'MELVIN HECKART'}});
  await prisma.user.create({data:{firstName: 'PRANAV BHATT'}});
  await prisma.user.create({data:{firstName: 'AVISHEK ROY'}});
  await prisma.user.create({data:{firstName: 'MILIND DEDHIA'}});
  await prisma.user.create({data:{firstName: 'MICHAEL G OLARTE'}});
  await prisma.user.create({data:{firstName: 'FAISAL BALOCH'}});
  await prisma.user.create({data:{firstName: 'CHIRAG VYAS'}});
  await prisma.user.create({data:{firstName: 'NU VUE'}});
  await prisma.user.create({data:{firstName: 'MARK DULNIAK'}});
  await prisma.user.create({data:{firstName: 'DONALD MACK'}});
  await prisma.user.create({data:{firstName: 'THOMAS ULRICH'}});
  await prisma.user.create({data:{firstName: 'SAM PATEL'}});
  await prisma.user.create({data:{firstName: 'VIRGIL V BANNER'}});
  await prisma.user.create({data:{firstName: 'ERIC B SMITH'}});
  await prisma.user.create({data:{firstName: 'THOMAS ELLERBE'}});
  await prisma.user.create({data:{firstName: 'BOBBY CHEN'}});
  await prisma.user.create({data:{firstName: 'DENNIS PHILLIPS'}});
  await prisma.user.create({data:{firstName: 'CARL EDWARD SMITH'}});
  await prisma.user.create({data:{firstName: 'TRAVIS SCHELL'}});
  await prisma.user.create({data:{firstName: 'CHENGXI CHU'}});
  await prisma.user.create({data:{firstName: 'ADAM MAYES'}});
  await prisma.user.create({data:{firstName: 'RODNEY BOWERS'}});
  await prisma.user.create({data:{firstName: 'IMRAN KADER'}});
  await prisma.user.create({data:{firstName: 'GARY AUTHEMENT'}});
  await prisma.user.create({data:{firstName: 'RAHUL CHAODHARY'}});
  await prisma.user.create({data:{firstName: 'ARPIT SRIVASTAVA'}});
  await prisma.user.create({data:{firstName: 'ARVIND KUMAR'}});
  await prisma.user.create({data:{firstName: 'AKHILESH SEMWAL'}});
  await prisma.user.create({data:{firstName: 'ASMITA DEBROY'}});
  await prisma.user.create({data:{firstName: 'ROBERT WHITTED'}});
  await prisma.user.create({data:{firstName: 'MARK KELLY'}});
  await prisma.user.create({data:{firstName: 'WILLIAM BLOCKER'}});
  await prisma.user.create({data:{firstName: 'DAVID YARBER'}});
  await prisma.user.create({data:{firstName: 'TERESITA FLORES'}});
  await prisma.user.create({data:{firstName: 'CAREN GRAY-WYNN'}});
  await prisma.user.create({data:{firstName: 'MICHAEL HARDY'}});
  await prisma.user.create({data:{firstName: 'JEFFREY DREWS'}});
  await prisma.user.create({data:{firstName: 'TIMOTHY PIPER'}});
  await prisma.user.create({data:{firstName: 'MICHAEL LAVESPERE'}});
  await prisma.user.create({data:{firstName: 'DARRIN L DAIGLE'}});
  await prisma.user.create({data:{firstName: 'RINO RISI'}});
  await prisma.user.create({data:{firstName: 'LARRY D PIERCE'}});
  await prisma.user.create({data:{firstName: 'JOSEPH RAZAL'}});
  await prisma.user.create({data:{firstName: 'STANLEY ADAMS'}});
  await prisma.user.create({data:{firstName: 'MARK L HOLLEN'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER MIDDLETON'}});
  await prisma.user.create({data:{firstName: 'TARUN SETHI'}});
  await prisma.user.create({data:{firstName: 'DAVID SMITH'}});
  await prisma.user.create({data:{firstName: 'RACHANA D KHATKHATE'}});
  await prisma.user.create({data:{firstName: 'DARRELL F GLOVER'}});
  await prisma.user.create({data:{firstName: 'MANUEL BALDONADO'}});
  await prisma.user.create({data:{firstName: 'MARC KNAPP'}});
  await prisma.user.create({data:{firstName: 'CHRISTOPHER  BRANTLEY'}});
  await prisma.user.create({data:{firstName: 'RODOLFO QUANT'}});
  await prisma.user.create({data:{firstName: 'ANKIT MODI'}});
  await prisma.user.create({data:{firstName: 'NARENDRA NATH SAMANTA'}});
  await prisma.user.create({data:{firstName: 'JOSE', lastName: 'NINAHAUMAN'}});
  await prisma.user.create({data:{firstName: 'DAVID', lastName: 'CONIGLIO'}});
  await prisma.user.create({data:{firstName: 'JOHN', lastName: 'KUEHNE'}});
  await prisma.user.create({data:{firstName: 'WILLIAM COMPTON'}});
  await prisma.user.create({data:{firstName: 'SHAHALI SHARIF'}});
  await prisma.user.create({data:{firstName: 'JASON PAULLEY'}});
  await prisma.user.create({data:{firstName: 'JASON TYRE'}});
  await prisma.user.create({data:{firstName: 'BRANDON MATHISON'}});
  await prisma.user.create({data:{firstName: 'AJAY CHHAJED'}});
  await prisma.user.create({data:{firstName: 'WILLIE HALBERT'}});
  await prisma.user.create({data:{firstName: 'LAURA CARPENTER'}});
  await prisma.user.create({data:{firstName: 'LEE PATTERSON'}});
  await prisma.user.create({data:{firstName: 'HANK HUANG'}});
  await prisma.user.create({data:{firstName: 'ARIF QURESHI'}});
  await prisma.user.create({data:{firstName: 'ANIBAL RAMIREZ'}});
  await prisma.user.create({data:{firstName: 'WIEDY GUNAWAN'}});
  await prisma.user.create({data:{firstName: 'RICHARD C BREBNER'}});
  await prisma.user.create({data:{firstName: 'EVENS MICHEL'}});
  await prisma.user.create({data:{firstName: 'PRATYUSH PRASUN'}});
  await prisma.user.create({data:{firstName: 'MEL DOUGLAS'}});
  await prisma.user.create({data:{firstName: 'ED GUTIERREZ'}});
  await prisma.user.create({data:{firstName: 'SYED U AHMED'}});
  await prisma.user.create({data:{firstName: 'LEEWEI YEH'}});
  await prisma.user.create({data:{firstName: 'BENJAMIN ESTEVA'}});
  await prisma.user.create({data:{firstName: 'FRED VIERNES'}});
  await prisma.user.create({data:{firstName: 'JEBOK KIM'}});
  await prisma.user.create({data:{firstName: 'LOWELL KICKLITER'}});
  await prisma.user.create({data:{firstName: 'ASIF RAFIQ'}});
  await prisma.user.create({data:{firstName: 'JON STAUFFER'}});
  await prisma.user.create({data:{firstName: 'WAYNE JONES'}});
  await prisma.user.create({data:{firstName: 'JOSUE DUVERNA'}});
  await prisma.user.create({data:{firstName: 'MARIA Martinez'}});
  await prisma.user.create({data:{firstName: 'AMAD MOTAZEDIAN'}});
  await prisma.user.create({data:{firstName: 'RAJESH KUMAR GOLA'}});
  await prisma.user.create({data:{firstName: 'TROYCE GILL'}});
  await prisma.user.create({data:{firstName: 'CRAIG SUE'}});
  await prisma.user.create({data:{firstName: 'YOUSSOUF MOHAMED'}});
  await prisma.user.create({data:{firstName: 'NATHAN FOGARTY'}});
  await prisma.user.create({data:{firstName: 'AJEESH MP'}});
  await prisma.user.create({data:{firstName: 'FRANK BAYLON'}});
  await prisma.user.create({data:{firstName: 'VINCENT CAPUTO'}});
  await prisma.user.create({data:{firstName: 'DAVID HEROD'}});
  await prisma.user.create({data:{firstName: 'FRANCISCO PARADAS'}});
  await prisma.user.create({data:{firstName: 'STEVEN WARD'}});
  await prisma.user.create({data:{firstName: 'FADY ISSHAK'}});
  await prisma.user.create({data:{firstName: 'MAHFUZUL HAQUE'}});
  await prisma.user.create({data:{firstName: 'SHAILESH KUMAR CHAURASIA'}});
  await prisma.user.create({data:{firstName: 'RAUL X RAMOS-QUINTANA'}});
  await prisma.user.create({data:{firstName: 'RAFAEL A VAZQUEZ'}});
  await prisma.user.create({data:{firstName: 'JOHN W PROCK'}});
  await prisma.user.create({data:{firstName: 'SIMON ZUNIGA'}});
  await prisma.user.create({data:{firstName: 'XAVIER B GARZA'}});
  await prisma.user.create({data:{firstName: 'JOE REYNA JR'}});
  await prisma.user.create({data:{firstName: 'RICHARD CRAIG'}});
  await prisma.user.create({data:{firstName: 'SRIRAM RAMAMOORTHY'}});
  await prisma.user.create({data:{firstName: 'MERCY LUHANGA'}});
  await prisma.user.create({data:{firstName: 'SEAN CHANDLER'}});
  await prisma.user.create({data:{firstName: 'HOWARD (Kelly) KREKEL'}});
  await prisma.user.create({data:{firstName: 'DON BERKLEY'}});
  await prisma.user.create({data:{firstName: 'RICHARD ALAN BROWN'}});
  await prisma.user.create({data:{firstName: 'SREENIVAS VEMULA'}});
  await prisma.user.create({data:{firstName: 'JOHN STEHR'}});
  await prisma.user.create({data:{firstName: 'SRINU X VEMULA'}});
  await prisma.user.create({data:{firstName: 'TODD IVIE'}});
  await prisma.user.create({data:{firstName: 'CLYDE A CHAPPELL'}});
  await prisma.user.create({data:{firstName: 'RACHID FADLALLAH'}});
  await prisma.user.create({data:{firstName: 'LUKE L CARNAGEY'}});
  await prisma.user.create({data:{firstName: 'VIRENDER PAL SINGH'}});
  await prisma.user.create({data:{firstName: 'NAV SHARMA'}});
  await prisma.user.create({data:{firstName: 'QUMARS EGHANEYAN'}});
  await prisma.user.create({data:{firstName: 'KEITH MENAWI'}});
  await prisma.user.create({data:{firstName: 'TEJINDER  SINGH'}});
  await prisma.user.create({data:{firstName: 'MICHAEL VILLA'}});
  await prisma.user.create({data:{firstName: 'SANJAY SHENOY'}});
  await prisma.user.create({data:{firstName: 'MAULIK SHAH'}});
  await prisma.user.create({data:{firstName: 'NIKHIL LUTHRA'}});
  await prisma.user.create({data:{firstName: 'JUAN PORTILLO'}});
  await prisma.user.create({data:{firstName: 'SYED RAZA HASAN'}});
  await prisma.user.create({data:{firstName: 'IVAN BURGOS'}});
  await prisma.user.create({data:{firstName: 'SWETASHILPI D GHOSH'}});
  await prisma.user.create({data:{firstName: 'SHARAREH EKBATANI'}});
  await prisma.user.create({data:{firstName: 'CARLOS APONTE'}});
  await prisma.user.create({data:{firstName: 'DANILO SABACAN'}});
  await prisma.user.create({data:{firstName: 'DAVID  LOWE'}});
  await prisma.user.create({data:{firstName: 'MOHAMMED A JEWEL'}});
  await prisma.user.create({data:{firstName: 'AMARNATH WARI'}});
  await prisma.user.create({data:{firstName: 'ANUJA CHAAND'}});
  await prisma.user.create({data:{firstName: 'PAT HIRST'}});
  await prisma.user.create({data:{firstName: 'ROGELIO LEGAL'}});
  await prisma.user.create({data:{firstName: 'ADITYA KEDIA'}});
  await prisma.user.create({data:{firstName: 'HANAFI BRADAI'}});
  await prisma.user.create({data:{firstName: 'MATHEW C THEISZ'}});
  await prisma.user.create({data:{firstName: 'KABIR AINI'}});
  await prisma.user.create({data:{firstName: 'FARID ARDAKANI'}});
  await prisma.user.create({data:{firstName: 'VISHAL PADIYAR'}});
  await prisma.user.create({data:{firstName: 'FRANCIS ESMI'}});
  await prisma.user.create({data:{firstName: 'JAWAD  SALAH-UD DIN'}});
  await prisma.user.create({data:{firstName: 'JOSEPH M GO'}});
  await prisma.user.create({data:{firstName: 'AIJAZ X YOUSUF'}});
  await prisma.user.create({data:{firstName: 'JITENDRA LATHI'}});
  await prisma.user.create({data:{firstName: 'MARK PETERSEN'}});
  await prisma.user.create({data:{firstName: 'RAYNER SILLOREQUEZ'}});
  await prisma.user.create({data:{firstName: 'NATHAN SUTTER'}});
  await prisma.user.create({data:{firstName: 'JARROD BASGALL'}});
  await prisma.user.create({data:{firstName: 'RICHARD TROBAUGH'}});
  await prisma.user.create({data:{firstName: 'KEVIN C FOO'}});
  await prisma.user.create({data:{firstName: 'JAMES HOPKINS'}});
  await prisma.user.create({data:{firstName: 'MATT K HOLTHE'}});
  await prisma.user.create({data:{firstName: 'RALPH J SCOPO'}});
  await prisma.user.create({data:{firstName: 'KEENAN HILL'}});
  await prisma.user.create({data:{firstName: 'TODD STONE'}});
  await prisma.user.create({data:{firstName: 'JOHN BYNUM'}});
  await prisma.user.create({data:{firstName: 'BIRENDRA NAYAK'}});
  await prisma.user.create({data:{firstName: 'DatabaseDependency'}});
  await prisma.user.create({data:{firstName: 'ADAM GRUENTHAL'}});
  await prisma.user.create({data:{firstName: 'MAX W CHESSHIR'}});
  await prisma.user.create({data:{firstName: 'TROY MATHIEU'}});
  await prisma.user.create({data:{firstName: 'ASHISH TULI'}});
  await prisma.user.create({data:{firstName: 'TOM PERANTEAU'}});
  await prisma.user.create({data:{firstName: 'TAM NGUYEN'}});
  await prisma.user.create({data:{firstName: 'SHAUNAE TRUSTY'}});
  await prisma.user.create({data:{firstName: 'LUNG CHANG'}});
  await prisma.user.create({data:{firstName: 'JOE F GONZALEZ'}});
  await prisma.user.create({data:{firstName: 'AKSHAY SHAH'}});
  await prisma.user.create({data:{firstName: 'TERRANCE GATES'}});
  await prisma.user.create({data:{firstName: 'MIKE RUIZ'}});
  await prisma.user.create({data:{firstName: 'JORDAN STOLTZ'}});
  await prisma.user.create({data:{firstName: 'DANIEL GEORGE'}});
  await prisma.user.create({data:{firstName: 'CLIFF GRIMES'}});
  await prisma.user.create({data:{firstName: 'ABHISHEK.KUMAR.AB.SINGH'}});
  await prisma.user.create({data:{firstName: 'MEHDI SOUISSI'}});
  await prisma.user.create({data:{firstName: 'IOK FAI CHIO'}});
  await prisma.user.create({data:{firstName: 'FAISAL KHAN'}});
  await prisma.user.create({data:{firstName: 'KAMLESH MEHTA'}});
  await prisma.user.create({data:{firstName: 'ISAIAS ALVARAN'}});
  await prisma.user.create({data:{firstName: 'RAFI R THAJUDEEN'}});
  await prisma.user.create({data:{firstName: 'MIRZA ASIF BEG'}});
  await prisma.user.create({data:{firstName: 'LAURA GONZALEZ'}});
  await prisma.user.create({data:{firstName: 'SIDDHARTH JAGANATH'}});
  await prisma.user.create({data:{firstName: 'RAEE NADKARNI'}});
  await prisma.user.create({data:{firstName: 'YONG CHEN'}});
  await prisma.user.create({data:{firstName: 'LAJJA BHAGAT'}});
  await prisma.user.create({data:{firstName: 'SHILPA  KOWDLEY'}});
  await prisma.user.create({data:{firstName: 'BILL FOWLER'}});
  await prisma.user.create({data:{firstName: 'KITIKORN PIPADNUDDA'}});
  await prisma.user.create({data:{firstName: 'RICHARD X CRAIG'}});
  await prisma.user.create({data:{firstName: 'ALLEN JAY FINE'}});
  await prisma.user.create({data:{firstName: 'ALLEN ANDERSON'}});
  await prisma.user.create({data:{firstName: 'NIKHIL ATRE'}});
  await prisma.user.create({data:{firstName: 'GREG REAGAN'}});
  await prisma.user.create({data:{firstName: 'BRYAN SMITH'}});
  await prisma.user.create({data:{firstName: 'ALI AYOUB'}});
  await prisma.user.create({data:{firstName: 'THOMAS', lastName: 'MURRAY'}});
  await prisma.user.create({data:{firstName: 'RICK', lastName: 'COLLINS'}});
  await prisma.user.create({data:{firstName: 'JOE', lastName: 'GOURLEY'}});
  await prisma.user.create({data:{firstName: 'DANTE', lastName: 'PULIATTI'}});
  await prisma.user.create({data:{firstName: 'ANDY', lastName: 'SLATER'}});
  await prisma.user.create({data:{firstName: 'RONALD', lastName: 'KENNEDY'}});
  await prisma.user.create({data:{firstName: 'DOUGLAS', lastName: 'KING'}});
  await prisma.user.create({data:{firstName: 'JOE', lastName: 'WERTHER'}});
  await prisma.user.create({data:{firstName: 'MARIA', lastName: 'MARTINEZ'}});
  await prisma.user.create({data:{firstName: 'MATTHEW', lastName: 'GREGORY'}});
  await prisma.user.create({data:{firstName: 'DEXTER', lastName: 'TORCULAS'}});
}

main()
  .catch((e: Error) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })